from __future__ import annotations

import fnmatch
import hashlib
import io
import json
import os
import re
import shutil
import sqlite3
import tempfile
import threading
import uuid
from math import ceil
from collections import Counter
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..common.formats import atomic_text_write, file_sha256
from ..common.language import has_han, is_translatable_bracket_tag
from ..common.translation_core import GeminiTranslator, TranslationConfig
from ..common.types import (
    CancellationToken,
    CancelledError,
    ProgressThrottle,
    QuotaExhaustedError,
    Reporter,
    ValidationError,
    null_reporter,
    report_progress,
)
from ..legend.pipeline import (
    LEGEND_PROFILE,
    _escape_legend_value,
    _split_legend_kv,
    _unescape_legend_value,
)

SCHEMA_VERSION = 1
EXTRACTOR_VERSION = 2
UTF8_BOM = b"\xef\xbb\xbf"
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 500

ALLOW_FIELDS = frozenset(
    {
        "dialog",
        "showText",
        "description",
        "description2",
        "name",
        "shortName",
        "progress",
        "winTips",
        "loseTips",
        "rewardTips",
        "conversation",
        "dialogNotify",
        "executeDialog",
        "region",
        "surname",
        "word",
        "chenghu",
    }
)
COMPOSITE_FIELDS = frozenset(
    {"option", "box", "aryEffectStr", "specialNI", "specialWO", "zuncheng"}
)
TECHNICAL_FIELD_RE = re.compile(
    r"^(?:condition|formula|activeCondition|failCondition|finishCondition|"
    r"randomPlace|randomNPC)",
    re.IGNORECASE,
)
LANGUAGE_SUFFIX_RE = re.compile(r"(?:Tc|En|Jp|Kr|Other)$")
PHASE_EFFECT_RE = re.compile(r"^phaseEffectStr\d*$")
STRUCTURAL_TOKEN_RE = re.compile(r"(?:@@@@@|&#&|&&)")
DSL_STRUCTURE_RE = re.compile(r"(?:@@@@@|&#&|&&+|/+|;)")
PROTECTED_TOKEN_RE = re.compile(
    r"(?:</?[^>\r\n]+>|\{[^{}\r\n]*\}|%(?:\d+\$)?[-+#0 ]*\d*(?:\.\d+)?[a-zA-Z]|\\[rnt])"
)
BRACKET_TAG_RE = re.compile(r"(?:\[[^\]\r\n]*\]|</?[^>\r\n]+>)")
RECORD_ID_FIELDS = ("id", "eventID", "groupID")
MAIN_TRANSLATION_FILENAME = "AutoGeneratedTranslations.txt"
RUNTIME_TRANSLATION_FILENAME = "_AutoGeneratedTranslations.txt"
MODEL_PRICING_USD_PER_MILLION: dict[str, tuple[float, float]] = {
    # https://ai.google.dev/gemini-api/docs/generate-content/latest-model
    "gemini-3.5-flash-lite": (0.30, 2.50),
    "gemini-3.6-flash": (1.50, 7.50),
}


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _text_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _canonical_hash(value: Any) -> str:
    return _text_hash(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")))


def _absolute_directory(path: Path, label: str) -> Path:
    if not path.is_absolute() or "\x00" in str(path):
        raise ValidationError(f"{label} phải là đường dẫn tuyệt đối hợp lệ")
    try:
        resolved = path.resolve(strict=True)
    except OSError as error:
        raise ValidationError(f"Không mở được {label}: {error}") from error
    if not resolved.is_dir():
        raise ValidationError(f"{label} không phải thư mục")
    return resolved


def _absolute_file(path: Path, label: str, *, must_exist: bool = True) -> Path:
    if not path.is_absolute() or "\x00" in str(path):
        raise ValidationError(f"{label} phải là đường dẫn tuyệt đối hợp lệ")
    resolved = path.resolve(strict=False)
    if must_exist and not resolved.is_file():
        raise ValidationError(f"Không tìm thấy {label}")
    if not must_exist and not resolved.parent.is_dir():
        raise ValidationError(f"Thư mục chứa {label} không tồn tại")
    return resolved


def _main_translation_path(path: Path, *, must_exist: bool = True) -> Path:
    resolved = _absolute_file(path, "mainPath", must_exist=must_exist)
    if resolved.name.casefold() != MAIN_TRANSLATION_FILENAME.casefold():
        raise ValidationError(
            f"mainPath phải trỏ đúng tới {MAIN_TRANSLATION_FILENAME}; "
            f"không được dùng {RUNTIME_TRANSLATION_FILENAME}"
        )
    return resolved


def _runtime_translation_path(path: Path, *, must_exist: bool = True) -> Path:
    resolved = _absolute_file(path, "runtimePath", must_exist=must_exist)
    if resolved.name.casefold() != RUNTIME_TRANSLATION_FILENAME.casefold():
        raise ValidationError(f"runtimePath phải trỏ đúng tới {RUNTIME_TRANSLATION_FILENAME}")
    return resolved


def iter_root_array(path: Path, *, chunk_size: int = 1024 * 1024) -> Iterator[tuple[int, Any]]:
    """Đọc từng phần tử root array, chấp nhận control character trong JSON string."""

    decoder = json.JSONDecoder(strict=False)
    with path.open("rb") as binary:
        stream = io.TextIOWrapper(binary, encoding="utf-8-sig", errors="strict", newline="")
        buffer = ""
        cursor = 0
        eof = False

        def read_more() -> bool:
            nonlocal buffer, eof
            chunk = stream.read(chunk_size)
            if chunk:
                buffer += chunk
                return True
            eof = True
            return False

        def ensure_content() -> None:
            nonlocal cursor
            while True:
                while cursor < len(buffer) and buffer[cursor].isspace():
                    cursor += 1
                if cursor < len(buffer) or eof:
                    return
                read_more()

        ensure_content()
        if cursor >= len(buffer) or buffer[cursor] != "[":
            raise ValidationError(f"JSON phải có root array: {path.name}")
        cursor += 1
        index = 0
        expecting_value = True
        while True:
            ensure_content()
            if cursor >= len(buffer):
                raise ValidationError(f"JSON root array chưa đóng: {path.name}")
            if buffer[cursor] == "]":
                cursor += 1
                break
            if not expecting_value:
                if buffer[cursor] != ",":
                    raise ValidationError(f"JSON thiếu dấu phẩy gần record {index}: {path.name}")
                cursor += 1
                ensure_content()
            while True:
                try:
                    value, end = decoder.raw_decode(buffer, cursor)
                    break
                except json.JSONDecodeError as error:
                    if eof:
                        raise ValidationError(
                            f"JSON lỗi gần record {index} ({error.msg}): {path.name}"
                        ) from error
                    read_more()
            yield index, value
            index += 1
            cursor = end
            expecting_value = False
            if cursor > chunk_size * 2:
                buffer = buffer[cursor:]
                cursor = 0

        while True:
            while cursor < len(buffer) and buffer[cursor].isspace():
                cursor += 1
            if cursor < len(buffer):
                raise ValidationError(f"JSON có dữ liệu sau root array: {path.name}")
            if eof or not read_more():
                break


@dataclass(frozen=True)
class ExtractedOccurrence:
    source: str
    pointer: str
    field: str
    record_id: str | None
    extractor: str
    classification: str
    context: str


@dataclass(frozen=True)
class PipelineRule:
    file_pattern: str
    field: str
    action: str


def _json_pointer(parts: Sequence[str | int]) -> str:
    encoded = [str(part).replace("~", "~0").replace("/", "~1") for part in parts]
    return "/" + "/".join(encoded)


def _default_field_action(field: str) -> str:
    if TECHNICAL_FIELD_RE.match(field) or LANGUAGE_SUFFIX_RE.search(field):
        return "exclude"
    if field in ALLOW_FIELDS:
        return "allow"
    if field in COMPOSITE_FIELDS or PHASE_EFFECT_RE.match(field):
        return "composite"
    return "classify"


def _rule_action(rules: Sequence[PipelineRule], file_name: str, field: str) -> str:
    action = _default_field_action(field)
    for rule in rules:
        if rule.field == field and fnmatch.fnmatch(file_name, rule.file_pattern):
            action = rule.action
    return action


def _plain_composite_text(text: str) -> tuple[list[str], bool]:
    if not has_han(text):
        return [], True
    if any(token in text for token in ("/", ";", "@", "&&", "&#&")):
        return [], False
    return [text], True


def _option_segments(text: str) -> tuple[list[str], bool]:
    if "&" not in text and "#" not in text:
        return _plain_composite_text(text)
    segments: list[str] = []
    chunks = text.split("#")
    for chunk in chunks:
        before_controls, separator, controls = chunk.partition("&&")
        candidates = [
            field.strip()
            for field in before_controls.strip("& ").split("&")
            if has_han(field.strip())
        ]
        if not candidates:
            if has_han(chunk):
                return [], False
            continue
        if separator and has_han(controls):
            return [], False
        segments.append(candidates[-1])
    return segments, bool(segments) or not has_han(text)


def _box_segments(text: str) -> tuple[list[str], bool]:
    segments: list[str] = []
    records = [record for record in text.split(";") if record.strip()]
    if not records:
        return _plain_composite_text(text)
    for record in records:
        fields = record.split("/")
        if len(fields) < 5:
            return [], False
        try:
            for coordinate in fields[:4]:
                float(coordinate)
        except ValueError:
            return [], False
        display_fields = [field.strip() for field in fields[4:] if field.strip()]
        if not display_fields or any(not has_han(field) for field in display_fields):
            return [], False
        segments.extend(display_fields)
    return segments, bool(segments)


def _record_composite_segments(field: str, text: str) -> tuple[list[str], bool]:
    layouts = {
        "specialNI": (3, (0, 1), 2, ()),
        "specialWO": (2, (0,), 1, ()),
        "zuncheng": (4, (0,), 1, (2, 3)),
    }
    field_count, id_indexes, display_index, numeric_indexes = layouts[field]
    segments: list[str] = []
    records = [record for record in text.split(";") if record.strip()]
    if not records:
        return _plain_composite_text(text)
    for record in records:
        body = record.removesuffix("@@@@@").strip()
        fields = body.split("/")
        if len(fields) != field_count:
            return [], False
        if any(not re.fullmatch(r"WJ\d+", fields[index]) for index in id_indexes):
            return [], False
        if any(not re.fullmatch(r"-?\d+", fields[index]) for index in numeric_indexes):
            return [], False
        candidate = fields[display_index].strip()
        if not candidate or not has_han(candidate):
            return [], False
        segments.append(candidate)
    return segments, bool(segments)


def _composite_segments(field: str, text: str) -> tuple[list[str], bool]:
    if field == "option":
        return _option_segments(text)
    if field == "box":
        return _box_segments(text)
    if field == "aryEffectStr":
        if "@@@@@" not in text:
            return _plain_composite_text(text)
        chunks = text.split("@@@@@")
        segments = [chunk.strip("& ;") for chunk in chunks if chunk.strip("& ;")]
        if any(not has_han(segment) for segment in segments):
            return [], False
        return segments, bool(segments) or not has_han(text)
    if PHASE_EFFECT_RE.match(field):
        return ([text] if has_han(text) else []), True
    if field in {"specialNI", "specialWO", "zuncheng"}:
        return _record_composite_segments(field, text)
    return [], False


def extract_record(
    record: Any,
    *,
    file_name: str,
    record_index: int,
    rules: Sequence[PipelineRule] = (),
    text_actions: Mapping[str, str] | None = None,
) -> list[ExtractedOccurrence]:
    result: list[ExtractedOccurrence] = []
    text_actions = text_actions or {}
    record_id: str | None = None
    if isinstance(record, Mapping):
        for candidate in RECORD_ID_FIELDS:
            if candidate in record and record[candidate] not in (None, ""):
                record_id = str(record[candidate])
                break

    def walk(value: Any, parts: list[str | int]) -> None:
        if isinstance(value, Mapping):
            for key, child in value.items():
                walk(child, [*parts, str(key)])
            return
        if isinstance(value, list):
            for child_index, child in enumerate(value):
                walk(child, [*parts, child_index])
            return
        if not isinstance(value, str) or not value.strip() or not has_han(value):
            return
        field = str(parts[-1]) if parts else ""
        text_action = text_actions.get(_text_hash(value))
        action = text_action or _rule_action(rules, file_name, field)
        is_composite_field = _default_field_action(field) == "composite"
        if action == "composite" or (
            is_composite_field and action == "allow" and text_action is None
        ):
            segments, recognized = _composite_segments(field, value)
            if not recognized:
                result.append(
                    ExtractedOccurrence(
                        value,
                        _json_pointer(parts),
                        field,
                        record_id,
                        "composite-unrecognized",
                        "classify",
                        value[:500],
                    )
                )
                return
            for segment_index, segment in enumerate(segments):
                classification = text_actions.get(_text_hash(segment), "allow")
                result.append(
                    ExtractedOccurrence(
                        segment,
                        f"{_json_pointer(parts)}#display/{segment_index}",
                        field,
                        record_id,
                        f"composite:{field}",
                        classification,
                        value[:500],
                    )
                )
            return
        result.append(
            ExtractedOccurrence(
                value,
                _json_pointer(parts),
                field,
                record_id,
                "field",
                action,
                value[:500],
            )
        )

    walk(record, [record_index])
    return result


def _connect(db_path: Path) -> sqlite3.Connection:
    if not db_path.is_absolute() or "\x00" in str(db_path):
        raise ValidationError("dbPath phải là đường dẫn tuyệt đối")
    db_path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(db_path, timeout=60)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    connection.execute("PRAGMA journal_mode = WAL")
    connection.execute("PRAGMA synchronous = NORMAL")
    _initialize_schema(connection)
    return connection


def _initialize_schema(connection: sqlite3.Connection) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS meta (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS scans (
            id TEXT PRIMARY KEY,
            source_root TEXT NOT NULL,
            started_at TEXT NOT NULL,
            completed_at TEXT,
            fingerprint TEXT,
            files_total INTEGER NOT NULL DEFAULT 0,
            files_parsed INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS inventory (
            path TEXT PRIMARY KEY,
            size INTEGER NOT NULL,
            mtime_ns INTEGER NOT NULL,
            sha256 TEXT NOT NULL,
            present INTEGER NOT NULL DEFAULT 1,
            last_scan_id TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS texts (
            source_hash TEXT PRIMARY KEY,
            source TEXT NOT NULL,
            target TEXT,
            status TEXT NOT NULL DEFAULT 'New',
            translation_source TEXT,
            accepted INTEGER NOT NULL DEFAULT 0,
            explicit_update INTEGER NOT NULL DEFAULT 0,
            model_fingerprint TEXT,
            first_seen_scan TEXT,
            last_seen_scan TEXT,
            orphan INTEGER NOT NULL DEFAULT 0,
            updated_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS occurrences (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            file_path TEXT NOT NULL,
            record_id TEXT,
            pointer TEXT NOT NULL,
            field TEXT NOT NULL,
            source_hash TEXT NOT NULL REFERENCES texts(source_hash),
            extractor TEXT NOT NULL,
            classification TEXT NOT NULL,
            context TEXT NOT NULL DEFAULT '',
            first_seen_scan TEXT NOT NULL,
            last_seen_scan TEXT NOT NULL,
            UNIQUE(file_path, pointer, source_hash)
        );
        CREATE INDEX IF NOT EXISTS occurrences_source_idx ON occurrences(source_hash);
        CREATE INDEX IF NOT EXISTS occurrences_file_idx ON occurrences(file_path);
        CREATE TABLE IF NOT EXISTS rules (
            file_pattern TEXT NOT NULL,
            field TEXT NOT NULL,
            action TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY(file_pattern, field)
        );
        CREATE TABLE IF NOT EXISTS text_overrides (
            source_hash TEXT PRIMARY KEY,
            action TEXT,
            target TEXT,
            accepted INTEGER NOT NULL DEFAULT 0,
            updated_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS translation_memory (
            source_hash TEXT PRIMARY KEY,
            source TEXT NOT NULL,
            target TEXT NOT NULL,
            origin TEXT NOT NULL,
            accepted INTEGER NOT NULL DEFAULT 1,
            profile_fingerprint TEXT,
            updated_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS previews (
            id TEXT PRIMARY KEY,
            scan_id TEXT NOT NULL,
            scan_fingerprint TEXT NOT NULL,
            source_root TEXT NOT NULL,
            main_path TEXT NOT NULL,
            main_fingerprint TEXT NOT NULL,
            inventory_snapshot TEXT NOT NULL,
            rendered BLOB NOT NULL,
            rendered_fingerprint TEXT NOT NULL,
            qa_json TEXT NOT NULL,
            created_at TEXT NOT NULL,
            applied_at TEXT
        );
        CREATE TABLE IF NOT EXISTS backups (
            id TEXT PRIMARY KEY,
            output_path TEXT NOT NULL,
            backup_path TEXT NOT NULL,
            manifest_path TEXT NOT NULL,
            before_fingerprint TEXT NOT NULL,
            applied_fingerprint TEXT NOT NULL,
            created_at TEXT NOT NULL
        );
        """
    )
    connection.execute(
        "INSERT INTO meta(key, value) VALUES('schema_version', ?) "
        "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
        (str(SCHEMA_VERSION),),
    )
    connection.commit()


def _load_rules(connection: sqlite3.Connection) -> list[PipelineRule]:
    return [PipelineRule(row["file_pattern"], row["field"], row["action"]) for row in connection.execute(
        "SELECT file_pattern, field, action FROM rules ORDER BY rowid"
    )]


def _load_text_actions(connection: sqlite3.Connection) -> dict[str, str]:
    return {
        row["source_hash"]: row["action"]
        for row in connection.execute("SELECT source_hash, action FROM text_overrides WHERE action IS NOT NULL")
    }


def _ensure_text(
    connection: sqlite3.Connection,
    source: str,
    scan_id: str | None,
    classification: str,
) -> str:
    source_hash = _text_hash(source)
    existing = connection.execute(
        "SELECT source FROM texts WHERE source_hash=?", (source_hash,)
    ).fetchone()
    if existing is not None and existing["source"] != source:
        raise ValidationError("Phát hiện va chạm SHA-256 không mong đợi")
    status = {"allow": "New", "exclude": "Excluded", "classify": "Needs classification"}.get(
        classification, "Needs classification"
    )
    connection.execute(
        """
        INSERT INTO texts(source_hash, source, status, first_seen_scan, last_seen_scan, updated_at)
        VALUES(?, ?, ?, ?, ?, ?)
        ON CONFLICT(source_hash) DO UPDATE SET
            last_seen_scan=COALESCE(excluded.last_seen_scan, texts.last_seen_scan),
            updated_at=excluded.updated_at
        """,
        (source_hash, source, status, scan_id, scan_id, _utc_now()),
    )
    return source_hash


def _parse_xunity(path: Path | None) -> tuple[bytes, bool, str, list[dict[str, Any]]]:
    if path is None or not path.is_file():
        return b"", False, "\r\n", []
    raw = path.read_bytes()
    has_bom = raw.startswith(UTF8_BOM)
    payload = raw[len(UTF8_BOM) :] if has_bom else raw
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ValidationError(f"File XUnity không phải UTF-8 hợp lệ: {path}") from error
    newline = "\r\n" if "\r\n" in text else ("\n" if "\n" in text else "\r\n")
    rows: list[dict[str, Any]] = []
    offset = 0
    for line_number, raw_line in enumerate(text.splitlines(keepends=True), 1):
        ending = "\r\n" if raw_line.endswith("\r\n") else (raw_line[-1] if raw_line.endswith(("\n", "\r")) else "")
        body = raw_line[: -len(ending)] if ending else raw_line
        pair = _split_legend_kv(body)
        if pair is not None and not body.lstrip().startswith(("#", ";", "//")):
            left, right = pair
            rows.append(
                {
                    "line": line_number,
                    "start": offset,
                    "end": offset + len(raw_line),
                    "body": body,
                    "ending": ending,
                    "left": left,
                    "right": right,
                    "source": _unescape_legend_value(left),
                    "target": _unescape_legend_value(right),
                }
            )
        offset += len(raw_line)
    if text and not text.endswith(("\n", "\r")):
        # splitlines(keepends=True) đã tạo dòng cuối; offset vẫn chính xác.
        pass
    return raw, has_bom, newline, rows


def _valid_translation(source: str, target: str) -> bool:
    return bool(target.strip()) and target.strip() != source.strip()


def _import_xunity(
    connection: sqlite3.Connection,
    main_path: Path | None,
    runtime_path: Path | None,
) -> tuple[int, int, set[str]]:
    main_count = 0
    runtime_count = 0
    conflicts: set[str] = set()
    _raw, _bom, _newline, main_rows = _parse_xunity(main_path)
    targets_by_hash: dict[str, set[str]] = {}
    for row in main_rows:
        source = row["source"]
        target = row["target"]
        source_hash = _ensure_text(connection, source, None, "allow")
        if target.strip():
            targets_by_hash.setdefault(source_hash, set()).add(target)
        if _valid_translation(source, target):
            manual = connection.execute(
                """
                SELECT target FROM text_overrides
                WHERE source_hash=? AND accepted=1 AND target IS NOT NULL AND target<>''
                """,
                (source_hash,),
            ).fetchone()
            if manual is None:
                connection.execute(
                    """
                    UPDATE texts SET target=?, status='Translated', translation_source='main',
                        accepted=1, explicit_update=0, model_fingerprint=NULL, updated_at=?
                    WHERE source_hash=?
                    """,
                    (target, _utc_now(), source_hash),
                )
                connection.execute(
                    """
                    INSERT INTO translation_memory(
                        source_hash, source, target, origin, accepted, updated_at
                    ) VALUES(?, ?, ?, 'main', 1, ?)
                    ON CONFLICT(source_hash) DO UPDATE SET target=excluded.target, origin='main',
                        accepted=1, profile_fingerprint=NULL, updated_at=excluded.updated_at
                    """,
                    (source_hash, source, target, _utc_now()),
                )
            main_count += 1
    for source_hash, targets in targets_by_hash.items():
        nonempty = {target for target in targets if target.strip()}
        if len(nonempty) > 1:
            conflicts.add(source_hash)
            connection.execute("UPDATE texts SET status='Conflict' WHERE source_hash=?", (source_hash,))

    manual_rows = connection.execute(
        """
        SELECT o.source_hash, o.target, t.source
        FROM text_overrides o JOIN texts t ON t.source_hash=o.source_hash
        WHERE o.accepted=1 AND o.target IS NOT NULL AND o.target<>''
        """
    ).fetchall()
    for manual in manual_rows:
        source_hash = manual["source_hash"]
        target = manual["target"]
        current_main_targets = targets_by_hash.get(source_hash, set())
        explicit_update = int(current_main_targets != {target})
        connection.execute(
            """
            UPDATE texts SET target=?, status=?, translation_source='manual', accepted=1,
                explicit_update=?, model_fingerprint=NULL, updated_at=? WHERE source_hash=?
            """,
            (
                target,
                "Conflict" if source_hash in conflicts else "Translated",
                explicit_update,
                _utc_now(),
                source_hash,
            ),
        )
        connection.execute(
            """
            INSERT INTO translation_memory(source_hash, source, target, origin, accepted, updated_at)
            VALUES(?, ?, ?, 'manual', 1, ?)
            ON CONFLICT(source_hash) DO UPDATE SET target=excluded.target, origin='manual',
                accepted=1, profile_fingerprint=NULL, updated_at=excluded.updated_at
            """,
            (source_hash, manual["source"], target, _utc_now()),
        )

    _raw, _bom, _newline, runtime_rows = _parse_xunity(runtime_path)
    for row in runtime_rows:
        source = row["source"]
        target = row["target"]
        if not _valid_translation(source, target):
            continue
        source_hash = _ensure_text(connection, source, None, "allow")
        current = connection.execute(
            "SELECT accepted FROM texts WHERE source_hash=?", (source_hash,)
        ).fetchone()
        if current is not None and not current["accepted"]:
            connection.execute(
                """
                UPDATE texts SET target=?, status='Needs review', translation_source='runtime',
                    accepted=0, updated_at=? WHERE source_hash=?
                """,
                (target, _utc_now(), source_hash),
            )
            runtime_count += 1
    return main_count, runtime_count, conflicts


def _recompute_text_states(connection: sqlite3.Connection, scan_id: str) -> None:
    rows = connection.execute(
        """
        SELECT t.source_hash, t.target, t.accepted, t.translation_source, t.status,
               SUM(CASE WHEN o.last_seen_scan=? AND o.classification='allow' THEN 1 ELSE 0 END) AS allows,
               SUM(CASE WHEN o.last_seen_scan=? AND o.classification='classify' THEN 1 ELSE 0 END) AS classifies,
               SUM(CASE WHEN o.last_seen_scan=? THEN 1 ELSE 0 END) AS active_occurrences
        FROM texts t LEFT JOIN occurrences o ON o.source_hash=t.source_hash
        GROUP BY t.source_hash
        """,
        (scan_id, scan_id, scan_id),
    ).fetchall()
    for row in rows:
        orphan = int(row["active_occurrences"] or 0) == 0
        status = row["status"]
        if status == "Conflict":
            pass
        elif (
            int(row["active_occurrences"] or 0) > 0
            and int(row["allows"] or 0) == 0
            and int(row["classifies"] or 0) == 0
        ):
            status = "Excluded"
        elif row["accepted"] and row["target"]:
            status = "Translated"
        elif row["target"] and not row["accepted"]:
            status = "Needs review"
        elif int(row["allows"] or 0) > 0:
            status = "New"
        elif int(row["classifies"] or 0) > 0:
            status = "Needs classification"
        else:
            status = "Excluded"
        connection.execute(
            "UPDATE texts SET status=?, orphan=?, last_seen_scan=CASE WHEN ?=0 THEN last_seen_scan ELSE ? END WHERE source_hash=?",
            (status, int(orphan), int(row["active_occurrences"] or 0), scan_id, row["source_hash"]),
        )


def _scan_fingerprint(connection: sqlite3.Connection) -> str:
    rows = connection.execute(
        "SELECT path, size, mtime_ns, sha256 FROM inventory WHERE present=1 ORDER BY path"
    ).fetchall()
    return _canonical_hash([dict(row) for row in rows])


def scan_pipeline(
    source_root: Path,
    db_path: Path,
    *,
    main_path: Path | None = None,
    runtime_path: Path | None = None,
    profile_fingerprint: str | None = None,
    reporter: Reporter = null_reporter,
    cancel: CancellationToken | None = None,
) -> dict[str, Any]:
    cancel = cancel or CancellationToken()
    source_root = _absolute_directory(source_root, "sourceRoot")
    main_path = _main_translation_path(main_path) if main_path is not None else None
    runtime_path = (
        _runtime_translation_path(runtime_path, must_exist=runtime_path.exists())
        if runtime_path is not None
        else None
    )
    if main_path is not None and runtime_path is not None and main_path == runtime_path:
        raise ValidationError("mainPath và runtimePath không được trỏ cùng một file")
    files = sorted(source_root.rglob("*.json"), key=lambda item: item.as_posix().lower())
    if not files:
        raise ValidationError("Không tìm thấy file JSON trong sourceRoot")
    scan_id = str(uuid.uuid4())
    started_at = _utc_now()
    progress = ProgressThrottle()
    parsed_files = 0
    reused_files = 0
    occurrence_count = 0
    connection = _connect(db_path)
    try:
        stored_extractor_version = connection.execute(
            "SELECT value FROM meta WHERE key='extractor_version'"
        ).fetchone()
        force_reparse = (
            stored_extractor_version is None
            or stored_extractor_version["value"] != str(EXTRACTOR_VERSION)
        )
        connection.execute(
            "INSERT INTO scans(id, source_root, started_at, files_total) VALUES(?, ?, ?, ?)",
            (scan_id, str(source_root), started_at, len(files)),
        )
        previously_present = {
            row["path"]
            for row in connection.execute("SELECT path FROM inventory WHERE present=1")
        }
        connection.execute("UPDATE inventory SET present=0")
        rules = _load_rules(connection)
        text_actions = _load_text_actions(connection)
        for file_index, path in enumerate(files, 1):
            cancel.check()
            relative = path.relative_to(source_root).as_posix()
            stat = path.stat()
            previous = connection.execute("SELECT * FROM inventory WHERE path=?", (relative,)).fetchone()
            unchanged = (
                previous is not None
                and not force_reparse
                and relative in previously_present
                and previous["size"] == stat.st_size
                and previous["mtime_ns"] == stat.st_mtime_ns
            )
            if unchanged:
                sha256 = previous["sha256"]
                reused_files += 1
                connection.execute(
                    "UPDATE occurrences SET last_seen_scan=? WHERE file_path=?",
                    (scan_id, relative),
                )
            else:
                sha256 = file_sha256(path)
                same_content = (
                    previous is not None
                    and not force_reparse
                    and previous["sha256"] == sha256
                )
                if same_content:
                    reused_files += 1
                    connection.execute(
                        "UPDATE occurrences SET last_seen_scan=? WHERE file_path=?",
                        (scan_id, relative),
                    )
                else:
                    parsed_files += 1
                    old_first_seen = {
                        (row["pointer"], row["source_hash"]): row["first_seen_scan"]
                        for row in connection.execute(
                            "SELECT pointer, source_hash, first_seen_scan FROM occurrences WHERE file_path=?",
                            (relative,),
                        )
                    }
                    connection.execute("DELETE FROM occurrences WHERE file_path=?", (relative,))
                    for record_index, record in iter_root_array(path):
                        cancel.check()
                        for occurrence in extract_record(
                            record,
                            file_name=path.name,
                            record_index=record_index,
                            rules=rules,
                            text_actions=text_actions,
                        ):
                            source_hash = _ensure_text(
                                connection, occurrence.source, scan_id, occurrence.classification
                            )
                            first_seen = old_first_seen.get((occurrence.pointer, source_hash), scan_id)
                            connection.execute(
                                """
                                INSERT INTO occurrences(
                                    file_path, record_id, pointer, field, source_hash, extractor,
                                    classification, context, first_seen_scan, last_seen_scan
                                ) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                                """,
                                (
                                    relative,
                                    occurrence.record_id,
                                    occurrence.pointer,
                                    occurrence.field,
                                    source_hash,
                                    occurrence.extractor,
                                    occurrence.classification,
                                    occurrence.context,
                                    first_seen,
                                    scan_id,
                                ),
                            )
                            occurrence_count += 1
            connection.execute(
                """
                INSERT INTO inventory(path, size, mtime_ns, sha256, present, last_scan_id)
                VALUES(?, ?, ?, ?, 1, ?)
                ON CONFLICT(path) DO UPDATE SET size=excluded.size, mtime_ns=excluded.mtime_ns,
                    sha256=excluded.sha256, present=1, last_scan_id=excluded.last_scan_id
                """,
                (relative, stat.st_size, stat.st_mtime_ns, sha256, scan_id),
            )
            if file_index % 5 == 0 or file_index == len(files):
                report_progress(
                    reporter,
                    "inspect",
                    {
                        "phase": "legend-json-scan",
                        "processed": file_index,
                        "total": len(files),
                        "file": relative,
                        "scanId": scan_id,
                    },
                    progress,
                    force=True,
                )

        main_entries, runtime_entries, conflicts = _import_xunity(connection, main_path, runtime_path)
        if profile_fingerprint:
            connection.execute(
                """
                UPDATE texts SET status='Needs review', accepted=0
                WHERE translation_source='model' AND accepted=1
                  AND COALESCE(model_fingerprint, '') <> ?
                """,
                (profile_fingerprint,),
            )
            connection.execute(
                """
                UPDATE translation_memory SET accepted=0
                WHERE origin='model' AND accepted=1
                  AND COALESCE(profile_fingerprint, '') <> ?
                """,
                (profile_fingerprint,),
            )
        _recompute_text_states(connection, scan_id)
        for source_hash in conflicts:
            connection.execute("UPDATE texts SET status='Conflict' WHERE source_hash=?", (source_hash,))
        fingerprint = _scan_fingerprint(connection)
        connection.execute(
            "UPDATE scans SET completed_at=?, fingerprint=?, files_parsed=? WHERE id=?",
            (_utc_now(), fingerprint, parsed_files, scan_id),
        )
        for key, value in (
            ("latest_scan_id", scan_id),
            ("latest_scan_fingerprint", fingerprint),
            ("source_root", str(source_root)),
            ("main_path", str(main_path) if main_path else ""),
            ("runtime_path", str(runtime_path) if runtime_path else ""),
            ("extractor_version", str(EXTRACTOR_VERSION)),
        ):
            connection.execute(
                "INSERT INTO meta(key, value) VALUES(?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",
                (key, value),
            )
        connection.commit()
        stats = _status_counts(connection)
        return {
            "scanId": scan_id,
            "fingerprint": fingerprint,
            "sourceRoot": str(source_root),
            "files": len(files),
            "parsedFiles": parsed_files,
            "reusedFiles": reused_files,
            "occurrencesParsed": occurrence_count,
            "mainEntriesImported": main_entries,
            "runtimeEntriesImported": runtime_entries,
            "stats": stats,
        }
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def _meta(connection: sqlite3.Connection, key: str) -> str | None:
    row = connection.execute("SELECT value FROM meta WHERE key=?", (key,)).fetchone()
    return row["value"] if row else None


def _require_scan(connection: sqlite3.Connection) -> tuple[str, str]:
    scan_id = _meta(connection, "latest_scan_id")
    fingerprint = _meta(connection, "latest_scan_fingerprint")
    if not scan_id or not fingerprint:
        raise ValidationError("Hãy chạy Scan JSON trước")
    return scan_id, fingerprint


def _display_status_sql() -> str:
    return "CASE WHEN t.orphan=1 THEN 'Orphan' ELSE t.status END"


def _status_counts(connection: sqlite3.Connection) -> dict[str, int]:
    rows = connection.execute(
        f"SELECT {_display_status_sql()} AS display_status, COUNT(*) AS count FROM texts t GROUP BY display_status"
    ).fetchall()
    result = {
        "New": 0,
        "Translated": 0,
        "Needs review": 0,
        "Needs classification": 0,
        "Excluded": 0,
        "Orphan": 0,
        "Conflict": 0,
    }
    result.update({row["display_status"]: int(row["count"]) for row in rows})
    result["total"] = sum(value for key, value in result.items() if key != "total")
    return result


def list_pipeline_entries(
    db_path: Path,
    *,
    offset: int = 0,
    limit: int = DEFAULT_PAGE_SIZE,
    status: str | None = None,
    search: str = "",
    source_hash: str | None = None,
) -> dict[str, Any]:
    if offset < 0 or not 1 <= limit <= MAX_PAGE_SIZE:
        raise ValidationError(f"offset/limit không hợp lệ; limit tối đa {MAX_PAGE_SIZE}")
    connection = _connect(db_path)
    try:
        scan_id, fingerprint = _require_scan(connection)
        if source_hash:
            text_row = connection.execute(
                f"SELECT t.*, {_display_status_sql()} AS display_status FROM texts t WHERE source_hash=?",
                (source_hash,),
            ).fetchone()
            if text_row is None:
                raise ValidationError("Không tìm thấy text")
            occurrences = [
                dict(row)
                for row in connection.execute(
                    """
                    SELECT file_path AS file, record_id AS recordId, pointer, field, extractor,
                           classification, context, first_seen_scan AS firstSeenScan,
                           last_seen_scan AS lastSeenScan
                    FROM occurrences WHERE source_hash=? ORDER BY file_path, pointer
                    """,
                    (source_hash,),
                )
            ]
            return {
                "scanId": scan_id,
                "fingerprint": fingerprint,
                "entry": _entry_payload(text_row),
                "occurrences": occurrences,
            }
        clauses: list[str] = []
        params: list[Any] = []
        allowed_statuses = {
            "New",
            "Translated",
            "Needs review",
            "Needs classification",
            "Excluded",
            "Orphan",
            "Conflict",
        }
        if status and status != "All":
            if status not in allowed_statuses:
                raise ValidationError("Bộ lọc status không hợp lệ")
            clauses.append(f"{_display_status_sql()}=?")
            params.append(status)
        if search.strip():
            clauses.append("(t.source LIKE ? ESCAPE '\\' OR COALESCE(t.target, '') LIKE ? ESCAPE '\\')")
            escaped = search.strip().replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
            params.extend((f"%{escaped}%", f"%{escaped}%"))
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        total = int(connection.execute(f"SELECT COUNT(*) FROM texts t {where}", params).fetchone()[0])
        rows = connection.execute(
            f"""
            SELECT t.*, {_display_status_sql()} AS display_status,
                   COUNT(o.id) AS occurrence_count,
                   MIN(o.file_path) AS first_file,
                   MIN(o.field) AS first_field
            FROM texts t LEFT JOIN occurrences o ON o.source_hash=t.source_hash
            {where}
            GROUP BY t.source_hash
            ORDER BY CASE {_display_status_sql()}
                WHEN 'Conflict' THEN 0 WHEN 'Needs classification' THEN 1 WHEN 'New' THEN 2
                WHEN 'Needs review' THEN 3 WHEN 'Translated' THEN 4 WHEN 'Excluded' THEN 5 ELSE 6 END,
                t.updated_at DESC, t.source_hash
            LIMIT ? OFFSET ?
            """,
            (*params, limit, offset),
        ).fetchall()
        return {
            "scanId": scan_id,
            "fingerprint": fingerprint,
            "offset": offset,
            "limit": limit,
            "total": total,
            "items": [_entry_payload(row) for row in rows],
            "stats": _status_counts(connection),
        }
    finally:
        connection.close()


def _entry_payload(row: sqlite3.Row) -> dict[str, Any]:
    keys = set(row.keys())
    return {
        "sourceHash": row["source_hash"],
        "source": row["source"],
        "target": row["target"],
        "status": row["display_status"] if "display_status" in keys else row["status"],
        "translationSource": row["translation_source"],
        "accepted": bool(row["accepted"]),
        "explicitUpdate": bool(row["explicit_update"]),
        "occurrenceCount": int(row["occurrence_count"] or 0) if "occurrence_count" in keys else 0,
        "file": row["first_file"] if "first_file" in keys else None,
        "field": row["first_field"] if "first_field" in keys else None,
    }


def set_pipeline_rule(
    db_path: Path,
    *,
    file_pattern: str | None = None,
    field: str | None = None,
    action: str | None = None,
    source_hash: str | None = None,
    target: str | None = None,
    accepted: bool = False,
) -> dict[str, Any]:
    allowed_actions = {"allow", "exclude", "classify"}
    if action is not None and action not in allowed_actions:
        raise ValidationError("action phải là allow, exclude hoặc classify")
    connection = _connect(db_path)
    try:
        scan_id, fingerprint = _require_scan(connection)
        if source_hash:
            row = connection.execute("SELECT source FROM texts WHERE source_hash=?", (source_hash,)).fetchone()
            if row is None:
                raise ValidationError("Không tìm thấy sourceHash")
            if action is None and target is None:
                raise ValidationError("Override text cần action hoặc target")
            if target is not None and not target.strip():
                raise ValidationError("Target thủ công không được rỗng")
            if target is None:
                connection.execute(
                    """
                    INSERT INTO text_overrides(source_hash, action, accepted, updated_at)
                    VALUES(?, ?, 0, ?)
                    ON CONFLICT(source_hash) DO UPDATE SET action=excluded.action,
                        updated_at=excluded.updated_at
                    """,
                    (source_hash, action, _utc_now()),
                )
            else:
                connection.execute(
                    """
                    INSERT INTO text_overrides(source_hash, action, target, accepted, updated_at)
                    VALUES(?, ?, ?, ?, ?)
                    ON CONFLICT(source_hash) DO UPDATE SET
                        action=COALESCE(excluded.action, text_overrides.action),
                        target=excluded.target, accepted=excluded.accepted,
                        updated_at=excluded.updated_at
                    """,
                    (source_hash, action, target, int(accepted), _utc_now()),
                )
            if target is not None:
                connection.execute(
                    """
                    UPDATE texts SET target=?, status=?, translation_source='manual', accepted=?,
                        explicit_update=1, model_fingerprint=NULL, updated_at=? WHERE source_hash=?
                    """,
                    (target, "Translated" if accepted else "Needs review", int(accepted), _utc_now(), source_hash),
                )
                if accepted:
                    connection.execute(
                        """
                        INSERT INTO translation_memory(source_hash, source, target, origin, accepted, updated_at)
                        VALUES(?, ?, ?, 'manual', 1, ?)
                        ON CONFLICT(source_hash) DO UPDATE SET target=excluded.target, origin='manual',
                            accepted=1, updated_at=excluded.updated_at
                        """,
                        (source_hash, row["source"], target, _utc_now()),
                    )
            if action:
                connection.execute(
                    "UPDATE occurrences SET classification=? WHERE source_hash=?",
                    (action, source_hash),
                )
        else:
            if not file_pattern or not field or action is None:
                raise ValidationError("Rule field cần filePattern, field và action")
            connection.execute(
                """
                INSERT INTO rules(file_pattern, field, action, updated_at) VALUES(?, ?, ?, ?)
                ON CONFLICT(file_pattern, field) DO UPDATE SET action=excluded.action, updated_at=excluded.updated_at
                """,
                (file_pattern, field, action, _utc_now()),
            )
            rows = connection.execute("SELECT id, file_path FROM occurrences WHERE field=?", (field,)).fetchall()
            ids = [row["id"] for row in rows if fnmatch.fnmatch(Path(row["file_path"]).name, file_pattern)]
            connection.executemany(
                "UPDATE occurrences SET classification=? WHERE id=?",
                ((action, occurrence_id) for occurrence_id in ids),
            )
        _recompute_text_states(connection, scan_id)
        connection.commit()
        return {"scanId": scan_id, "fingerprint": fingerprint, "stats": _status_counts(connection)}
    finally:
        connection.close()


def _eligible_rows(
    connection: sqlite3.Connection,
    *,
    hashes: Sequence[str] | None = None,
    status: str = "New",
    search: str = "",
) -> list[sqlite3.Row]:
    clauses = ["t.orphan=0", "t.status=?", "EXISTS(SELECT 1 FROM occurrences o WHERE o.source_hash=t.source_hash AND o.classification='allow')"]
    params: list[Any] = [status]
    if hashes:
        placeholders = ",".join("?" for _ in hashes)
        clauses.append(f"t.source_hash IN ({placeholders})")
        params.extend(hashes)
    if search.strip():
        clauses.append("(t.source LIKE ? OR COALESCE(t.target, '') LIKE ?)")
        params.extend((f"%{search.strip()}%", f"%{search.strip()}%"))
    return connection.execute(
        f"SELECT t.* FROM texts t WHERE {' AND '.join(clauses)} ORDER BY t.source_hash", params
    ).fetchall()


def estimate_pipeline(
    db_path: Path,
    *,
    batch_size: int = 40,
    model: str | None = None,
    hashes: Sequence[str] | None = None,
    status: str = "New",
    search: str = "",
) -> dict[str, Any]:
    if batch_size < 1:
        raise ValidationError("batchSize phải lớn hơn 0")
    connection = _connect(db_path)
    try:
        scan_id, fingerprint = _require_scan(connection)
        rows = _eligible_rows(connection, hashes=hashes, status=status, search=search)
        characters = sum(len(row["source"]) for row in rows)
        batches = (len(rows) + batch_size - 1) // batch_size
        estimated_input_tokens = ceil(characters * 1.35) + batches * 450 if rows else 0
        estimated_output_tokens = ceil(characters * 1.5) if rows else 0
        estimated_tokens = estimated_input_tokens + estimated_output_tokens
        normalized_model = (model or "").strip().casefold()
        rates = MODEL_PRICING_USD_PER_MILLION.get(normalized_model)
        estimated_cost = None
        if rates is not None:
            input_rate, output_rate = rates
            estimated_cost = round(
                (estimated_input_tokens * input_rate + estimated_output_tokens * output_rate)
                / 1_000_000,
                6,
            )
        return {
            "scanId": scan_id,
            "fingerprint": fingerprint,
            "items": len(rows),
            "characters": characters,
            "estimatedInputTokens": estimated_input_tokens,
            "estimatedOutputTokens": estimated_output_tokens,
            "estimatedTokens": estimated_tokens,
            "estimatedBatches": batches,
            "estimatedApiCalls": batches,
            "estimatedCostUsd": estimated_cost,
            "pricingModel": model,
            "pricingSource": (
                "Google Gemini API paid-tier text token pricing"
                if rates is not None
                else None
            ),
        }
    finally:
        connection.close()


def translate_pipeline(
    db_path: Path,
    config: TranslationConfig,
    *,
    hashes: Sequence[str] | None = None,
    status: str = "New",
    search: str = "",
    profile_fingerprint: str,
    force_retranslate: bool = False,
    reporter: Reporter = null_reporter,
    cancel: CancellationToken | None = None,
) -> dict[str, Any]:
    cancel = cancel or CancellationToken()
    connection = _connect(db_path)
    try:
        scan_id, fingerprint = _require_scan(connection)
        if not force_retranslate:
            connection.execute(
                """
                UPDATE texts SET status='Needs review', accepted=0, updated_at=?
                WHERE translation_source='model' AND accepted=1
                  AND COALESCE(model_fingerprint, '') <> ?
                """,
                (_utc_now(), profile_fingerprint),
            )
            connection.execute(
                """
                UPDATE translation_memory SET accepted=0, updated_at=?
                WHERE origin='model' AND accepted=1
                  AND COALESCE(profile_fingerprint, '') <> ?
                """,
                (_utc_now(), profile_fingerprint),
            )
        rows = _eligible_rows(connection, hashes=hashes, status=status, search=search)
        reused = 0
        pending: list[sqlite3.Row] = []
        for row in rows:
            if force_retranslate:
                pending.append(row)
                continue
            tm = connection.execute(
                """
                SELECT target, origin, profile_fingerprint FROM translation_memory
                WHERE source_hash=? AND accepted=1
                """,
                (row["source_hash"],),
            ).fetchone()
            if tm is None:
                pending.append(row)
                continue
            if tm["origin"] == "model" and tm["profile_fingerprint"] != profile_fingerprint:
                pending.append(row)
                continue
            connection.execute(
                """
                UPDATE texts SET target=?, status='Translated', translation_source=?, accepted=1,
                    explicit_update=0, updated_at=? WHERE source_hash=?
                """,
                (tm["target"], tm["origin"], _utc_now(), row["source_hash"]),
            )
            reused += 1
        connection.commit()
        translated_count = 0
        stats: dict[str, Any] = {"apiCalls": 0, "cacheHits": 0}
        if pending:
            pending_by_hash = {row["source_hash"]: row for row in pending}
            persisted: set[str] = set()
            persist_lock = threading.Lock()

            def persist_batch(done: Mapping[str, str]) -> None:
                nonlocal translated_count
                persist_connection = _connect(db_path)
                try:
                    added_hashes: list[str] = []
                    with persist_lock:
                        for source_hash, raw_target in done.items():
                            if source_hash in persisted:
                                continue
                            row = pending_by_hash.get(source_hash)
                            if row is None:
                                continue
                            target = str(raw_target).strip()
                            if not target or target == row["source"]:
                                continue
                            persist_connection.execute(
                                """
                                UPDATE texts SET target=?, status='Translated',
                                    translation_source='model', accepted=1, explicit_update=?,
                                    model_fingerprint=?, updated_at=? WHERE source_hash=?
                                """,
                                (
                                    target,
                                    int(force_retranslate),
                                    profile_fingerprint,
                                    _utc_now(),
                                    source_hash,
                                ),
                            )
                            persist_connection.execute(
                                """
                                INSERT INTO translation_memory(
                                    source_hash, source, target, origin, accepted,
                                    profile_fingerprint, updated_at
                                ) VALUES(?, ?, ?, 'model', 1, ?, ?)
                                ON CONFLICT(source_hash) DO UPDATE SET
                                    target=excluded.target, origin='model', accepted=1,
                                    profile_fingerprint=excluded.profile_fingerprint,
                                    updated_at=excluded.updated_at
                                """,
                                (
                                    source_hash,
                                    row["source"],
                                    target,
                                    profile_fingerprint,
                                    _utc_now(),
                                ),
                            )
                            added_hashes.append(source_hash)
                    persist_connection.commit()
                    if added_hashes:
                        with persist_lock:
                            persisted.update(added_hashes)
                            translated_count += len(added_hashes)
                finally:
                    persist_connection.close()

            translator = GeminiTranslator(
                config,
                LEGEND_PROFILE,
                reporter=reporter,
                cancel=cancel,
                event_step="translate",
                fail_on_item_error=True,
            )
            items = [{"id": row["source_hash"], "text": row["source"]} for row in pending]
            try:
                translations = translator.translate_items(
                    items,
                    "legend",
                    "Legend JSON",
                    skip_cache=force_retranslate,
                    on_translated_batch=persist_batch,
                )
                persist_batch(translations)
            except (CancelledError, QuotaExhaustedError, ValidationError):
                translator.save_cache()
                partial = getattr(translator, "_partial_translations", {}) or {}
                if partial:
                    persist_batch(partial)
                raise
            translator.save_cache()
            stats = translator.stats.to_dict()
        return {
            "scanId": scan_id,
            "fingerprint": fingerprint,
            "selected": len(rows),
            "translated": translated_count,
            "reused": reused,
            "stats": stats,
            "statusCounts": _status_counts(connection),
        }
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def _inventory_snapshot(connection: sqlite3.Connection) -> list[dict[str, Any]]:
    return [
        dict(row)
        for row in connection.execute(
            "SELECT path, size, mtime_ns, sha256 FROM inventory WHERE present=1 ORDER BY path"
        )
    ]


def _bracket_tag_shape(tag: str) -> str:
    """Return the delimiter form, keeping opening and closing tags distinct."""
    return "</" if tag.startswith("</") else tag[0]


def _qa_translation(source: str, target: str) -> list[dict[str, str]]:
    issues: list[dict[str, str]] = []
    if not target.strip():
        issues.append({"severity": "error", "rule": "empty-target", "detail": "Target rỗng"})
        return issues
    source_fixed_tokens = Counter(
        token for token in PROTECTED_TOKEN_RE.findall(source) if not token.startswith("<")
    )
    target_fixed_tokens = Counter(
        token for token in PROTECTED_TOKEN_RE.findall(target) if not token.startswith("<")
    )
    source_tags = BRACKET_TAG_RE.findall(source)
    target_tags = BRACKET_TAG_RE.findall(target)
    tags_match = len(source_tags) == len(target_tags) and all(
        _bracket_tag_shape(source_tag) == _bracket_tag_shape(target_tag)
        and (is_translatable_bracket_tag(source_tag) or source_tag == target_tag)
        for source_tag, target_tag in zip(source_tags, target_tags)
    )
    if source_fixed_tokens != target_fixed_tokens or not tags_match:
        issues.append(
            {
                "severity": "error",
                "rule": "protected-token",
                "detail": "Placeholder/tag/token không còn khớp nguồn",
            }
        )
    has_composite_dsl = bool(
        STRUCTURAL_TOKEN_RE.search(source)
        or re.search(r"/{2,}", source)
        or re.search(r"(?:^|;)WJ\d+/", source)
    )
    source_structure = Counter(DSL_STRUCTURE_RE.findall(source)) if has_composite_dsl else Counter()
    if source_structure != (
        Counter(DSL_STRUCTURE_RE.findall(target)) if has_composite_dsl else Counter()
    ):
        issues.append(
            {
                "severity": "error",
                "rule": "composite-structure",
                "detail": "Delimiter composite/DSL bị thay đổi",
            }
        )
    if has_han(target):
        issues.append({"severity": "warning", "rule": "han-remaining", "detail": "Target còn chữ Hán"})
    if target.strip() == source.strip():
        issues.append({"severity": "warning", "rule": "same-as-source", "detail": "Target giống nguồn"})
    return issues


def _render_xunity(
    main_path: Path,
    translations: Sequence[sqlite3.Row],
) -> tuple[bytes, list[dict[str, Any]], list[dict[str, str]]]:
    raw, has_bom, newline, rows = _parse_xunity(main_path)
    payload = raw[len(UTF8_BOM) :] if has_bom else raw
    text = payload.decode("utf-8")
    existing_by_source: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        existing_by_source.setdefault(row["source"], []).append(row)
    issues: list[dict[str, str]] = []
    for source, duplicates in existing_by_source.items():
        targets = {row["target"] for row in duplicates if row["target"].strip()}
        if len(targets) > 1:
            issues.append(
                {
                    "severity": "error",
                    "rule": "source-conflict",
                    "source": source,
                    "detail": "Cùng source có nhiều target trong file chính",
                }
            )
    replacements: dict[int, str] = {}
    additions: list[str] = []
    changes: list[dict[str, Any]] = []
    for translation in translations:
        source = translation["source"]
        target = translation["target"] or ""
        existing = existing_by_source.get(source, [])
        if existing and not translation["explicit_update"]:
            continue
        row_issues = _qa_translation(source, target)
        for issue in row_issues:
            issues.append({**issue, "source": source, "sourceHash": translation["source_hash"]})
        if existing:
            for row in existing:
                replacements[row["line"]] = f"{row['left']}={_escape_legend_value(target)}{row['ending']}"
                changes.append(
                    {
                        "kind": "update",
                        "sourceHash": translation["source_hash"],
                        "source": source,
                        "before": row["target"],
                        "after": target,
                        "line": row["line"],
                    }
                )
            continue
        if translation["orphan"]:
            continue
        additions.append(f"{_escape_legend_value(source)}={_escape_legend_value(target)}{newline}")
        changes.append(
            {
                "kind": "append",
                "sourceHash": translation["source_hash"],
                "source": source,
                "before": None,
                "after": target,
                "line": None,
            }
        )
    rendered_parts: list[str] = []
    for line_number, raw_line in enumerate(text.splitlines(keepends=True), 1):
        rendered_parts.append(replacements.get(line_number, raw_line))
    rendered = "".join(rendered_parts)
    if additions:
        if rendered and not rendered.endswith(("\n", "\r")):
            rendered += newline
        rendered += "".join(additions)
    encoded = (UTF8_BOM if has_bom else b"") + rendered.encode("utf-8")
    try:
        parsed_raw, parsed_bom, parsed_newline, parsed_rows = _parse_xunity_bytes(encoded)
    except (OSError, UnicodeError, ValidationError) as error:
        issues.append({"severity": "error", "rule": "encoding-roundtrip", "detail": str(error)})
    else:
        if parsed_raw != encoded or parsed_bom != has_bom:
            issues.append(
                {"severity": "error", "rule": "encoding-roundtrip", "detail": "UTF-8 không round-trip"}
            )
        if additions and parsed_newline != newline:
            issues.append(
                {
                    "severity": "error",
                    "rule": "newline-roundtrip",
                    "detail": "Kiểu newline thay đổi sau serialization",
                }
            )
        expected_row_count = len(rows) + len(additions)
        if len(parsed_rows) != expected_row_count:
            issues.append(
                {
                    "severity": "error",
                    "rule": "serialization-roundtrip",
                    "detail": (
                        f"Kỳ vọng {expected_row_count} entry nhưng đọc lại được "
                        f"{len(parsed_rows)}"
                    ),
                }
            )
        parsed_targets: dict[str, list[str]] = {}
        for row in parsed_rows:
            parsed_targets.setdefault(row["source"], []).append(row["target"])
        checked: set[tuple[str, str]] = set()
        for change in changes:
            key = (change["source"], change["after"])
            if key in checked:
                continue
            checked.add(key)
            if change["after"] not in parsed_targets.get(change["source"], []):
                issues.append(
                    {
                        "severity": "error",
                        "rule": "serialization-roundtrip",
                        "source": change["source"],
                        "sourceHash": change["sourceHash"],
                        "detail": "Source/target không đọc lại đúng sau serialization",
                    }
                )
    return encoded, changes, issues


def preview_pipeline(
    db_path: Path,
    source_root: Path,
    main_path: Path,
) -> dict[str, Any]:
    source_root = _absolute_directory(source_root, "sourceRoot")
    main_path = _main_translation_path(main_path)
    connection = _connect(db_path)
    try:
        scan_id, scan_fingerprint = _require_scan(connection)
        scanned_root = _meta(connection, "source_root")
        if scanned_root != str(source_root):
            raise ValidationError("sourceRoot không khớp lần Scan gần nhất")
        scanned_main = _meta(connection, "main_path")
        if scanned_main and Path(scanned_main).resolve(strict=False) != main_path:
            raise ValidationError("mainPath không khớp lần Scan gần nhất; hãy Scan lại")
        translations = connection.execute(
            """
            SELECT * FROM texts
            WHERE accepted=1 AND target IS NOT NULL AND target<>''
              AND status NOT IN ('Needs review', 'Needs classification', 'Excluded', 'Conflict')
            ORDER BY source_hash
            """
        ).fetchall()
        rendered, changes, issues = _render_xunity(main_path, translations)
        qa = {
            "blocking": any(issue["severity"] == "error" for issue in issues),
            "errors": sum(issue["severity"] == "error" for issue in issues),
            "warnings": sum(issue["severity"] == "warning" for issue in issues),
            "issues": issues,
        }
        preview_id = str(uuid.uuid4())
        rendered_fingerprint = hashlib.sha256(rendered).hexdigest()
        main_fingerprint = file_sha256(main_path)
        inventory_snapshot = _inventory_snapshot(connection)
        connection.execute(
            """
            INSERT INTO previews(
                id, scan_id, scan_fingerprint, source_root, main_path, main_fingerprint,
                inventory_snapshot, rendered, rendered_fingerprint, qa_json, created_at
            ) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                preview_id,
                scan_id,
                scan_fingerprint,
                str(source_root),
                str(main_path),
                main_fingerprint,
                json.dumps(inventory_snapshot, ensure_ascii=False),
                rendered,
                rendered_fingerprint,
                json.dumps(qa, ensure_ascii=False),
                _utc_now(),
            ),
        )
        connection.commit()
        return {
            "previewId": preview_id,
            "scanId": scan_id,
            "fingerprint": scan_fingerprint,
            "mainFingerprint": main_fingerprint,
            "outputFingerprint": rendered_fingerprint,
            "mainPath": str(main_path),
            "changes": changes,
            "changeCount": len(changes),
            "qa": qa,
        }
    finally:
        connection.close()


def _assert_inventory_current(source_root: Path, snapshot: Sequence[Mapping[str, Any]]) -> None:
    current_paths = {
        path.relative_to(source_root).as_posix(): path
        for path in source_root.rglob("*.json")
    }
    expected_paths = {str(row["path"]): row for row in snapshot}
    if current_paths.keys() != expected_paths.keys():
        raise ValidationError("Danh sách JSON đã thay đổi sau Preview")
    for relative, expected in expected_paths.items():
        stat = current_paths[relative].stat()
        if stat.st_size != int(expected["size"]) or stat.st_mtime_ns != int(expected["mtime_ns"]):
            raise ValidationError(f"JSON đã thay đổi sau Preview: {relative}")
        if file_sha256(current_paths[relative]) != expected["sha256"]:
            raise ValidationError(f"Nội dung JSON đã thay đổi sau Preview: {relative}")


def _atomic_replace_bytes(path: Path, content: bytes) -> None:
    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb", prefix=f".{path.name}.", suffix=".tmp", dir=path.parent, delete=False
        ) as handle:
            temp_path = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if temp_path.read_bytes() != content:
            raise ValidationError("Xác minh file tạm thất bại")
        os.replace(temp_path, path)
        temp_path = None
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)


def _error_source_hashes(issues: Sequence[Mapping[str, Any]]) -> set[str]:
    return {
        str(issue["sourceHash"])
        for issue in issues
        if issue.get("severity") == "error" and issue.get("sourceHash")
    }


def _load_accepted_translations(
    connection: sqlite3.Connection,
    *,
    skip_hashes: set[str] | frozenset[str] = frozenset(),
) -> list[sqlite3.Row]:
    rows = connection.execute(
        """
        SELECT * FROM texts
        WHERE accepted=1 AND target IS NOT NULL AND target<>''
          AND status NOT IN ('Needs review', 'Needs classification', 'Excluded', 'Conflict')
        ORDER BY source_hash
        """
    ).fetchall()
    if not skip_hashes:
        return list(rows)
    return [row for row in rows if row["source_hash"] not in skip_hashes]


def _render_skipping_errors(
    main_path: Path,
    connection: sqlite3.Connection,
    *,
    skip_hashes: set[str],
) -> tuple[bytes, list[dict[str, Any]], list[dict[str, Any]], set[str]]:
    skipped = set(skip_hashes)
    for _ in range(8):
        kept = _load_accepted_translations(connection, skip_hashes=skipped)
        rendered, changes, issues = _render_xunity(main_path, kept)
        extra = _error_source_hashes(issues) - skipped
        if extra:
            skipped |= extra
            continue
        return rendered, changes, issues, skipped
    raise ValidationError("Không thể loại hết lỗi từng dòng")


def apply_pipeline(
    db_path: Path,
    preview_id: str,
    backup_dir: Path,
    *,
    skip_errors: bool = False,
) -> dict[str, Any]:
    if not preview_id:
        raise ValidationError("Thiếu previewId")
    connection = _connect(db_path)
    try:
        preview = connection.execute("SELECT * FROM previews WHERE id=?", (preview_id,)).fetchone()
        if preview is None:
            raise ValidationError("Không tìm thấy Preview")
        if preview["applied_at"]:
            raise ValidationError("Preview này đã được Apply")
        scan_id, scan_fingerprint = _require_scan(connection)
        if scan_id != preview["scan_id"] or scan_fingerprint != preview["scan_fingerprint"]:
            raise ValidationError("Preview/scan fingerprint đã cũ")
        qa = json.loads(preview["qa_json"])
        if qa.get("blocking") and not skip_errors:
            raise ValidationError("QA còn lỗi nghiêm trọng; Apply bị chặn")
        main_path = _main_translation_path(Path(preview["main_path"]))
        if file_sha256(main_path) != preview["main_fingerprint"]:
            raise ValidationError("File chính đã thay đổi sau Preview")
        source_root = _absolute_directory(Path(preview["source_root"]), "sourceRoot")
        _assert_inventory_current(source_root, json.loads(preview["inventory_snapshot"]))
        stored = bytes(preview["rendered"])
        if hashlib.sha256(stored).hexdigest() != preview["rendered_fingerprint"]:
            raise ValidationError("Preview serialization không còn hợp lệ")
        translations = _load_accepted_translations(connection)
        rerendered, rerun_changes, rerun_issues = _render_xunity(main_path, translations)
        if rerendered != stored:
            raise ValidationError("Dữ liệu bản dịch đã thay đổi sau Preview")
        skipped: set[str] = set()
        output = stored
        applied_changes = rerun_changes
        if skip_errors:
            skipped = _error_source_hashes(rerun_issues)
            if skipped:
                output, applied_changes, clean_issues, skipped = _render_skipping_errors(
                    main_path,
                    connection,
                    skip_hashes=skipped,
                )
                if any(issue.get("severity") == "error" for issue in clean_issues):
                    raise ValidationError(
                        "QA còn lỗi không bỏ được từng dòng; Apply phần sạch thất bại"
                    )
                if not applied_changes:
                    raise ValidationError("Không còn dòng OK để Apply")
            elif any(issue.get("severity") == "error" for issue in rerun_issues):
                raise ValidationError(
                    "QA lỗi không gắn được từng dòng; không thể Apply phần sạch"
                )
        elif any(issue["severity"] == "error" for issue in rerun_issues):
            raise ValidationError("QA lại trước Apply phát hiện lỗi nghiêm trọng")
        backup_dir = backup_dir.resolve(strict=False)
        backup_dir.mkdir(parents=True, exist_ok=True)
        backup_id = f"{datetime.now().strftime('%Y%m%d-%H%M%S')}-{uuid.uuid4().hex[:8]}"
        item_dir = backup_dir / backup_id
        item_dir.mkdir(parents=False, exist_ok=False)
        backup_path = item_dir / main_path.name
        shutil.copy2(main_path, backup_path)
        before_fingerprint = file_sha256(backup_path)
        applied_fingerprint = hashlib.sha256(output).hexdigest()
        manifest_path = item_dir / "manifest.json"
        manifest = {
            "version": 1,
            "id": backup_id,
            "createdAt": _utc_now(),
            "outputPath": str(main_path),
            "backupPath": str(backup_path),
            "beforeFingerprint": before_fingerprint,
            "appliedFingerprint": applied_fingerprint,
            "previewId": preview_id,
        }
        atomic_text_write(manifest_path, json.dumps(manifest, ensure_ascii=False, indent=2))
        _atomic_replace_bytes(main_path, output)
        if file_sha256(main_path) != applied_fingerprint:
            _atomic_replace_bytes(main_path, backup_path.read_bytes())
            raise ValidationError("Xác minh sau atomic replace thất bại; đã phục hồi backup")
        try:
            connection.execute(
                """
                INSERT INTO backups(id, output_path, backup_path, manifest_path, before_fingerprint,
                                    applied_fingerprint, created_at)
                VALUES(?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    backup_id,
                    str(main_path),
                    str(backup_path),
                    str(manifest_path),
                    before_fingerprint,
                    applied_fingerprint,
                    manifest["createdAt"],
                ),
            )
            connection.execute(
                "UPDATE previews SET applied_at=? WHERE id=?", (_utc_now(), preview_id)
            )
            changed_hashes = sorted({change["sourceHash"] for change in applied_changes})
            connection.executemany(
                "UPDATE texts SET explicit_update=0, updated_at=? WHERE source_hash=?",
                ((_utc_now(), source_hash) for source_hash in changed_hashes),
            )
            connection.commit()
        except Exception:
            connection.rollback()
            _atomic_replace_bytes(main_path, backup_path.read_bytes())
            raise
        accepted_hashes = {row["source_hash"] for row in translations}
        return {
            "previewId": preview_id,
            "backupId": backup_id,
            "backupPath": str(backup_path),
            "manifestPath": str(manifest_path),
            "outputPath": str(main_path),
            "outputFingerprint": applied_fingerprint,
            "appliedCount": len(changed_hashes),
            "skippedCount": len(skipped & accepted_hashes),
            "instruction": "Nhấn Alt+R trong game hoặc khởi động lại game để nạp bản dịch.",
        }
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def _parse_xunity_bytes(raw: bytes) -> tuple[bytes, bool, str, list[dict[str, Any]]]:
    with tempfile.TemporaryDirectory(prefix="legend-json-qa-") as directory:
        path = Path(directory) / "preview.txt"
        path.write_bytes(raw)
        return _parse_xunity(path)


def restore_pipeline(db_path: Path, backup_id: str, *, force: bool = False) -> dict[str, Any]:
    connection = _connect(db_path)
    try:
        backup = connection.execute("SELECT * FROM backups WHERE id=?", (backup_id,)).fetchone()
        if backup is None:
            raise ValidationError("Không tìm thấy backup")
        output_path = _main_translation_path(Path(backup["output_path"]))
        backup_path = _absolute_file(Path(backup["backup_path"]), "backupPath")
        if not force and file_sha256(output_path) != backup["applied_fingerprint"]:
            raise ValidationError("File hiện tại đã thay đổi sau Apply; cần xác nhận force để Restore")
        content = backup_path.read_bytes()
        if hashlib.sha256(content).hexdigest() != backup["before_fingerprint"]:
            raise ValidationError("Backup fingerprint không hợp lệ")
        _atomic_replace_bytes(output_path, content)
        if file_sha256(output_path) != backup["before_fingerprint"]:
            raise ValidationError("Xác minh Restore thất bại")
        return {
            "backupId": backup_id,
            "outputPath": str(output_path),
            "fingerprint": backup["before_fingerprint"],
            "restored": True,
        }
    finally:
        connection.close()


def list_backups(db_path: Path) -> dict[str, Any]:
    connection = _connect(db_path)
    try:
        items: list[dict[str, Any]] = []
        for row in connection.execute(
            """
            SELECT id, output_path, backup_path, manifest_path, before_fingerprint,
                   applied_fingerprint, created_at
            FROM backups
            ORDER BY created_at DESC, id DESC
            """
        ):
            backup_path = Path(row["backup_path"])
            valid = backup_path.is_file()
            if valid:
                try:
                    valid = file_sha256(backup_path) == row["before_fingerprint"]
                except OSError:
                    valid = False
            items.append(
                {
                    "id": row["id"],
                    "createdAt": row["created_at"],
                    "outputPath": str(row["output_path"]),
                    "backupPath": str(backup_path),
                    "manifestPath": row["manifest_path"],
                    "beforeFingerprint": row["before_fingerprint"],
                    "appliedFingerprint": row["applied_fingerprint"],
                    "valid": valid,
                }
            )
        return {"items": items, "total": len(items)}
    finally:
        connection.close()
