import type { AppState } from "@/lib/app-types"

export const demoState: AppState = {
  setupComplete: true,
  syncApplied: true,
  syncPreview: {
    fingerprint: "demo-fingerprint-abc123",
    createdAt: new Date(Date.now() - 3 * 60_000).toISOString(),
  },
  selectedStep: "translate",
  steps: [
    {
      id: "export",
      title: "Export dữ liệu tiếng Anh",
      shortTitle: "Export",
      description: "Quét dữ liệu gốc và tạo bản export an toàn theo cấu trúc game.",
      status: "success",
      lastRun: "Hôm nay, 00:14",
      duration: "01:42",
      summary: { files: 1_284, rows: 48_219 },
    },
    {
      id: "inspect",
      title: "Kiểm tra & Thống kê",
      shortTitle: "Kiểm tra",
      description: "Đối chiếu EN–VN, kiểm tra XML/VTT và lập báo cáo chênh lệch.",
      status: "warning",
      lastRun: "Hôm nay, 00:17",
      duration: "00:38",
      summary: { files: 1_284, changes: 367, warnings: 12 },
    },
    {
      id: "sync",
      title: "Đồng bộ nội dung",
      shortTitle: "Đồng bộ",
      description:
        "Thêm/xóa file & dòng theo cấu trúc EN, giữ bản dịch VN đã có, backup rồi ghi atomic.",
      status: "success",
      lastRun: "Hôm nay, 00:21",
      duration: "02:08",
      summary: { changes: 367, files: 94 },
    },
    {
      id: "translate",
      title: "Dịch bằng Gemini",
      shortTitle: "Dịch",
      description: "Dịch theo batch với cache/resume; nhiều API key song song và fallback model.",
      status: "running",
      lastRun: "Đang chạy",
      summary: { translated: 7_842, warnings: 3 },
    },
    {
      id: "deploy",
      title: "Triển khai vào game",
      shortTitle: "Deploy",
      description: "Copy file .xml/.vtt từ mod VN sang thư mục game Steam, có backup.",
      status: "locked",
      lockedReason: "Cần hoàn tất Dịch.",
      summary: {},
    },
  ],
  activeJob: {
    id: "JOB-20260810-0021",
    step: "translate",
    status: "running",
    startedAt: "00:21",
    elapsed: "12:48",
    eta: "08:31",
    progress: 64,
    batchProgress: 72,
    currentFile: "DLC/yi-sun-sin/modules/text/en_us/AttributesText.xml",
    processed: 7_842,
    total: 12_306,
    throughput: "10,2 mục/giây",
    model: "gemini-3.5-flash-lite",
    keyId: "key-2",
  },
  events: [
    {
      id: "evt-6",
      seq: 106,
      timestamp: "00:33:48",
      level: "success",
      title: "Hoàn tất batch 196",
      description: "40 mục đã dịch, 7 mục lấy từ cache.",
      step: "translate",
    },
    {
      id: "evt-5",
      seq: 105,
      timestamp: "00:33:42",
      level: "info",
      title: "Đang dịch AttributesText.xml",
      description: "Batch 196/308 · 40 mục · gemini-3.5-flash-lite",
      step: "translate",
    },
    {
      id: "evt-4",
      seq: 104,
      timestamp: "00:32:11",
      level: "warning",
      title: "Đã chuyển sang API Phụ",
      description: "API Chính bị giới hạn tốc độ; tác vụ tiếp tục sau 2 giây.",
      step: "translate",
      detail: { reason: "HTTP 429", retryAfter: 2, keySuffix: "•••• 7K2M" },
    },
    {
      id: "evt-3",
      seq: 103,
      timestamp: "00:31:09",
      level: "success",
      title: "Cache đã được lưu",
      description: "Có thể tạm dừng và tiếp tục mà không dịch lại.",
      step: "translate",
    },
    {
      id: "evt-2",
      seq: 102,
      timestamp: "00:21:06",
      level: "info",
      title: "Đã nạp chuỗi fallback",
      description: "2 API key · 3 model · timeout 60 giây.",
      step: "translate",
    },
    {
      id: "evt-1",
      seq: 101,
      timestamp: "00:21:02",
      level: "info",
      title: "Bắt đầu tác vụ dịch",
      description: "Tìm thấy 12.306 mục cần xử lý.",
      step: "translate",
    },
  ],
  apiKeys: [
    {
      id: "key-1",
      label: "API Chính",
      maskedSuffix: "•••• A9P3",
      priority: 1,
      enabled: true,
      status: "rate-limited",
      lastUsed: "1 phút trước",
      localRequests: 148,
    },
    {
      id: "key-2",
      label: "API Phụ",
      maskedSuffix: "•••• 7K2M",
      priority: 2,
      enabled: true,
      status: "active",
      lastUsed: "Đang dùng",
      localRequests: 93,
      activeSince: "00:32",
    },
    {
      id: "key-3",
      label: "Dự phòng",
      maskedSuffix: "•••• Q4VX",
      priority: 3,
      enabled: true,
      status: "valid",
      lastUsed: "Hôm qua, 22:18",
      localRequests: 41,
    },
  ],
  syncChanges: [
    {
      id: "chg-1",
      kind: "add",
      file: "Base/Assets/Text/en_US/RootText.xml",
      tag: "LOC_EMPTY",
      after: "",
    },
    {
      id: "chg-1b",
      kind: "add",
      file: "Base/Assets/Text/en_US/RootText.xml",
      tag: "LOC_ROOT_NEW_HINT",
      after: "A new root hint string.",
    },
    {
      id: "chg-2",
      kind: "add",
      file: "base/modules/text/en_us/UnitText.xml",
      tag: "LOC_UNIT_COG_DESCRIPTION",
      after: "A naval transport unit with increased movement.",
    },
    {
      id: "chg-2b",
      kind: "delete",
      file: "base/modules/text/en_us/UnitText.xml",
      tag: "LOC_UNIT_LEGACY_NAME",
      before: "Đơn vị cũ",
    },
    {
      id: "chg-3",
      kind: "vtt",
      file: "DLC/nepal/modules/text/subtitles/civ_nepal_intro.vtt",
      tag: "00:00:02.100",
      after: "The mountains remember every promise.",
    },
    {
      id: "chg-4",
      kind: "delete",
      file: "base/modules/text/en_us/LegacyText.xml",
      tag: "LOC_LEGACY_UNUSED_DESCRIPTION",
      before: "Mô tả legacy không còn dùng.",
    },
    {
      id: "chg-5",
      kind: "add",
      file: "DLC/yi-sun-sin/modules/text/en_us/AttributesText.xml",
      tag: "LOC_ATTRIBUTE_NAVAL_COMMANDER_NAME",
      after: "Naval Commander",
    },
  ],
  deployChanges: [
    {
      id: "dep-1",
      kind: "copy",
      file: "Base\\modules\\text\\en_us\\UnitText.xml",
    },
    {
      id: "dep-2",
      kind: "create",
      file: "DLC\\yi-sun-sin\\modules\\text\\en_us\\AttributesText.xml",
    },
    {
      id: "dep-3",
      kind: "unchanged",
      file: "Base\\modules\\text\\en_us\\CivilopediaText.xml",
    },
  ],
  qaIssues: [
    {
      id: "qa-1",
      severity: "error",
      rule: "Mất token",
      file: "DLC/yi-sun-sin/modules/text/en_us/AbilityText.xml",
      tag: "LOC_ABILITY_TURTLE_SHIP_DESCRIPTION",
      source: "Gain {1_Amount} Combat Strength near a Coast.",
      target: "Nhận Sức mạnh Chiến đấu khi ở gần Bờ biển.",
    },
    {
      id: "qa-2",
      severity: "warning",
      rule: "Còn tiếng Anh",
      file: "base/modules/text/en_us/TutorialText.xml",
      tag: "LOC_TUTORIAL_COMMANDER_08",
      source: "Select a Commander to continue.",
      target: "Select a Commander để tiếp tục.",
    },
    {
      id: "qa-3",
      severity: "warning",
      rule: "Bản dịch quá dài",
      file: "DLC/nepal/modules/text/en_us/LegacyText.xml",
      tag: "LOC_LEGACY_NEPAL_CULTURE_DESCRIPTION",
      source: "Culture from Mountains.",
      target: "Nhận thêm một lượng Văn hóa đáng kể từ mọi ô Núi liền kề.",
    },
  ],
  reports: [
    {
      id: "report-4",
      step: "translate",
      title: "Dịch bằng Gemini",
      status: "paused",
      createdAt: "09/08/2026 · 23:41",
      duration: "18:20",
      summary: "5.420 mục đã dịch · tạm dừng do quota",
    },
    {
      id: "report-3",
      step: "sync",
      title: "Đồng bộ nội dung",
      status: "success",
      createdAt: "09/08/2026 · 23:18",
      duration: "02:12",
      summary: "351 thay đổi · 89 file · backup hợp lệ",
    },
    {
      id: "report-2",
      step: "inspect",
      title: "Kiểm tra & Thống kê",
      status: "warning",
      createdAt: "09/08/2026 · 23:15",
      duration: "00:41",
      summary: "351 chênh lệch · 9 cảnh báo",
    },
    {
      id: "report-1",
      step: "export",
      title: "Export dữ liệu tiếng Anh",
      status: "success",
      createdAt: "09/08/2026 · 23:12",
      duration: "01:49",
      summary: "1.279 file · 47.983 Row/Replace",
    },
  ],
  backups: [
    {
      id: "backup-3",
      createdAt: "Hôm nay · 00:19",
      step: "sync",
      files: 94,
      size: "18,4 MB",
      valid: true,
    },
    {
      id: "backup-2",
      createdAt: "09/08/2026 · 23:17",
      step: "sync",
      files: 89,
      size: "17,9 MB",
      valid: true,
    },
    {
      id: "backup-1",
      createdAt: "08/08/2026 · 21:04",
      step: "sync",
      files: 86,
      size: "17,1 MB",
      valid: false,
    },
  ],
  inspectSnapshot: {
    english: {
      xmlFiles: 1270,
      vttFiles: 14,
      rows: 47000,
      replaces: 1200,
      cues: 890,
      invalidCount: 2,
    },
    vietnamese: {
      xmlFiles: 1265,
      vttFiles: 14,
      rows: 46800,
      replaces: 1190,
      cues: 888,
      invalidCount: 10,
    },
    englishOnly: 42,
    vietnameseOnly: 8,
    differentFiles: 367,
    diffs: [
      {
        id: "inspect-0",
        file: "DLC/yi-sun-sin/modules/text/en_us/AbilityText.xml",
        status: "different",
        missingInVietnamese: [
          { type: "Row", tag: "LOC_ABILITY_TURTLE_SHIP", count: 1 },
        ],
        extraInVietnamese: [],
      },
      {
        id: "inspect-1",
        file: "base/modules/text/en_us/TutorialText.xml",
        status: "different",
        missingInVietnamese: [],
        extraInVietnamese: [
          { type: "Replace", tag: "LOC_TUTORIAL_OLD", count: 1 },
        ],
      },
      {
        id: "inspect-2",
        file: "DLC/new-civ/modules/text/en_us/LeaderText.xml",
        status: "english-only",
      },
      {
        id: "inspect-3",
        file: "base/modules/text/en_us/LegacyText.xml",
        status: "vietnamese-only",
      },
      {
        id: "inspect-4",
        file: "subtitles/en_us/intro.vtt",
        status: "different",
        missingInVietnamese: [{ timing: "00:01:12.000 --> 00:01:18.000", count: 1 }],
      },
      {
        id: "inspect-5",
        file: "base/modules/text/en_us/BrokenText.xml",
        status: "invalid",
        error: "mismatched tag: line 42, column 10",
      },
    ],
  },
  config: {
    gamePath: "B:\\SteamLibrary\\steamapps\\common\\Sid Meier's Civilization VII",
    exportPath: "C:\\Users\\NQT\\Desktop\\TOOL_GAME\\CIV7\\exported_files",
    modPath: "C:\\Users\\NQT\\Desktop\\TOOL_GAME\\CIV7\\CIV7VH",
    reportPath: "C:\\Users\\NQT\\Desktop\\SCRIPT",
    cachePath: "",
    glossaryPath: "C:\\Users\\NQT\\Desktop\\SCRIPT\\glossary.json",
    model: "gemini-3.5-flash-lite",
    fallbackModels: [
      "gemini-3.1-flash-lite",
      "gemini-3.6-flash",
      "gemini-3.5-flash",
    ],
    delayMs: 500,
    timeoutSeconds: 60,
    batchSize: 40,
    maxFiles: 0,
    maxApiCalls: 0,
    deployBackup: true,
    deployOnlyExisting: false,
    theme: "dark",
    themePreset: "indigo",
    notifications: {
      enabled: true,
      completed: true,
      paused: true,
      failed: true,
    },
  },
}
