import { describe, expect, it } from "vitest";
import {
  buildLegendJsonListConfig,
  inferLegendJsonPaths,
  isLegendJsonForceRestoreMessage,
  legendJsonApplySkipSummary,
  selectedHashesForRequest,
} from "@/lib/legend-json-types";

describe("Legend JSON path inference", () => {
  it("suy ra JSON và hai file XUnity từ deploy path", () => {
    expect(
      inferLegendJsonPaths(
        "B:\\SteamLibrary\\steamapps\\common\\LegendOfHeros\\BepInEx\\Translation\\vi\\Text\\AutoGeneratedTranslations.txt",
      ),
    ).toEqual({
      sourceRoot:
        "B:\\SteamLibrary\\steamapps\\common\\LegendOfHeros\\ThreeKingdom_Data\\StreamingAssets\\Json",
      mainPath:
        "B:\\SteamLibrary\\steamapps\\common\\LegendOfHeros\\BepInEx\\Translation\\vi\\Text\\AutoGeneratedTranslations.txt",
      runtimePath:
        "B:\\SteamLibrary\\steamapps\\common\\LegendOfHeros\\BepInEx\\Translation\\vi\\Text\\_AutoGeneratedTranslations.txt",
    });
  });
});

describe("Legend JSON selection", () => {
  it("gửi hash đã chọn hoặc toàn bộ bộ lọc", () => {
    const selected = new Set(["b", "a"]);
    expect(selectedHashesForRequest(selected, false)).toEqual(["b", "a"]);
    expect(selectedHashesForRequest(selected, true)).toBeUndefined();
  });

  it("tạo request phân trang, lọc và tìm kiếm phía backend", () => {
    expect(
      buildLegendJsonListConfig(3, 50, "Needs review", "  Lưu Bị  "),
    ).toEqual({
      offset: 100,
      limit: 50,
      status: "Needs review",
      search: "Lưu Bị",
    });
  });
});

describe("Legend JSON restore errors", () => {
  it("nhận diện lỗi fingerprint cần force restore", () => {
    expect(
      isLegendJsonForceRestoreMessage(
        "File hiện tại đã thay đổi sau Apply; cần xác nhận force để Restore",
      ),
    ).toBe(true);
    expect(isLegendJsonForceRestoreMessage("Không tìm thấy backup")).toBe(
      false,
    );
  });
});

describe("Legend JSON apply skip summary", () => {
  it("cho Apply dòng OK khi còn thay đổi sạch và lỗi gắn được từng dòng", () => {
    expect(
      legendJsonApplySkipSummary({
        changes: [
          {
            kind: "append",
            sourceHash: "ok",
            source: "原文",
            before: null,
            after: "Bản dịch",
            line: null,
          },
          {
            kind: "append",
            sourceHash: "bad",
            source: "#标题",
            before: null,
            after: "Tiêu đề",
            line: null,
          },
        ],
        qa: {
          blocking: true,
          errors: 1,
          warnings: 0,
          issues: [
            {
              severity: "error",
              rule: "serialization-roundtrip",
              detail: "không đọc lại đúng",
              source: "#标题",
              sourceHash: "bad",
            },
          ],
        },
      }),
    ).toEqual({
      errorHashCount: 1,
      cleanChangeCount: 1,
      canSkipApply: true,
    });
  });

  it("không cho Apply dòng OK khi mọi thay đổi đều lỗi", () => {
    expect(
      legendJsonApplySkipSummary({
        changes: [
          {
            kind: "append",
            sourceHash: "bad",
            source: "#标题",
            before: null,
            after: "Tiêu đề",
            line: null,
          },
        ],
        qa: {
          blocking: true,
          errors: 1,
          warnings: 0,
          issues: [
            {
              severity: "error",
              rule: "serialization-roundtrip",
              detail: "không đọc lại đúng",
              sourceHash: "bad",
            },
          ],
        },
      }).canSkipApply,
    ).toBe(false);
  });
});
