import { FolderOpenIcon } from "lucide-react";
import { PageHeader, pageContainerClass } from "@/components/product-ui";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import type { LegendTranslationController } from "@/hooks/use-legend-translation";
import { displayWindowsPath } from "@/lib/path-utils";

export function LegendSettingsPage({
  legend,
  locked = false,
}: {
  legend: LegendTranslationController;
  locked?: boolean;
}) {
  const busy =
    locked ||
    legend.globalJobActive ||
    legend.phase === "inspecting" ||
    legend.retranslating;

  return (
    <div className={pageContainerClass}>
      <PageHeader
        eyebrow="Legend of Heroes Three Kingdoms"
        title="Cài đặt"
        description="Chọn file nguồn XUnity và thư mục game. Trang Dịch dùng các đường dẫn này để kiểm tra, dịch và deploy."
      />

      <Card>
        <CardHeader>
          <CardTitle>File nguồn XUnity</CardTitle>
          <CardDescription>
            File được kiểm tra trước; bước dịch chỉ tạo artifact tạm và không
            sửa bản gốc.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <Field data-disabled={busy}>
            <FieldLabel htmlFor="legend-source-path">
              Đường dẫn file bản dịch
            </FieldLabel>
            <div className="flex flex-col gap-2 sm:flex-row">
              <Input
                id="legend-source-path"
                value={displayWindowsPath(legend.sourcePath)}
                disabled={busy}
                onChange={(event) =>
                  legend.setSourcePath(displayWindowsPath(event.target.value))
                }
              />
              <Button
                type="button"
                variant="outline"
                disabled={busy}
                onClick={() => void legend.chooseFile()}
              >
                <FolderOpenIcon data-icon="inline-start" />
                Chọn file
              </Button>
            </div>
            <FieldDescription>
              Hỗ trợ UTF-8/UTF-8 BOM và bảo toàn thứ tự, comment, regex, escape
              dấu bằng cùng CRLF/LF.
            </FieldDescription>
          </Field>

          <Field data-disabled={busy}>
            <FieldLabel htmlFor="legend-deploy-path">
              Thư mục game (deploy)
            </FieldLabel>
            <div className="flex flex-col gap-2 sm:flex-row">
              <Input
                id="legend-deploy-path"
                value={displayWindowsPath(legend.deployPath)}
                disabled={busy}
                placeholder="B:\SteamLibrary\steamapps\common\LegendOfHeros\BepInEx\Translation\vi\Text"
                onChange={(event) =>
                  legend.setDeployPath(displayWindowsPath(event.target.value))
                }
                onBlur={() => void legend.saveDeployPath()}
              />
              <Button
                type="button"
                variant="outline"
                disabled={busy}
                onClick={() => void legend.chooseDeployFolder()}
              >
                <FolderOpenIcon data-icon="inline-start" />
                Chọn thư mục
              </Button>
            </div>
            <FieldDescription>
              Khi áp dụng, bản dịch staged sẽ được backup và ghi đè{" "}
              <code>_AutoGeneratedTranslations.txt</code> trong thư mục này.
            </FieldDescription>
          </Field>
        </CardContent>
      </Card>
    </div>
  );
}
