import {
  act,
  cleanup,
  fireEvent,
  render,
  screen,
  waitFor,
} from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { LegendJsonPipelinePage } from "@/components/legend-json-pipeline-page";
import { useLegendJsonPipeline } from "@/hooks/use-legend-json-pipeline";
import { clearLegendJsonProgress } from "@/lib/legend-json-progress-store";
import type { LegendJsonListResult } from "@/lib/legend-json-types";
import type { LegendJobEvent } from "@/lib/legend-types";

const mocks = vi.hoisted(() => ({
  run: vi.fn(),
  cancel: vi.fn(),
  legendEventHandler: null as
    | ((event: Pick<LegendJobEvent, "jobId" | "type" | "payload">) => void)
    | null,
}));

vi.mock("sonner", () => ({
  toast: { success: vi.fn(), error: vi.fn(), info: vi.fn() },
}));

vi.mock("@/lib/tauri-ipc", () => ({
  formatInvokeError: (error: unknown) => {
    if (error instanceof Error) return error.message;
    if (typeof error === "string") return error;
    if (error && typeof error === "object" && "message" in error) {
      const message = (error as { message?: unknown }).message;
      if (typeof message === "string" && message.trim()) return message;
    }
    return String(error);
  },
  invokeErrorCode: (error: unknown) =>
    error && typeof error === "object" && "code" in error
      ? String((error as { code: unknown }).code)
      : null,
  ipc: {
    getLegendDeployPath: vi.fn().mockResolvedValue(null),
    runLegendJsonCommand: mocks.run,
    listenToLegendJobEvents: vi.fn().mockImplementation((handler) => {
      mocks.legendEventHandler = handler;
      return Promise.resolve(() => undefined);
    }),
    cancelJob: mocks.cancel,
    pickDirectory: vi.fn(),
    pickFile: vi.fn(),
  },
}));

function page(offset = 0): LegendJsonListResult {
  return {
    scanId: "scan-1",
    fingerprint: "fingerprint",
    offset,
    limit: 50,
    total: 60,
    items: [
      {
        sourceHash: `hash-${offset}`,
        source: `原文 ${offset}`,
        target: null,
        status: "New",
        translationSource: null,
        accepted: false,
        explicitUpdate: false,
        occurrenceCount: 2,
        file: "Game.json",
        field: "dialog",
      },
    ],
    stats: {
      New: 60,
      Translated: 0,
      "Needs review": 0,
      "Needs classification": 0,
      Excluded: 0,
      Orphan: 0,
      Conflict: 0,
      total: 60,
    },
  };
}

function translatedPage(): LegendJsonListResult {
  const result = page();
  return {
    ...result,
    total: 1,
    items: [
      {
        ...result.items[0],
        target: "Bản dịch 0",
        status: "Translated",
        translationSource: "model",
        accepted: true,
      },
    ],
    stats: {
      ...result.stats,
      New: 0,
      Translated: 1,
      total: 1,
    },
  };
}

function backupItem(id = "backup-1") {
  return {
    id,
    createdAt: "2026-08-21T00:00:00.000Z",
    outputPath: "C:\\AutoGeneratedTranslations.txt",
    backupPath: "C:\\backup.txt",
    manifestPath: "C:\\manifest.json",
    beforeFingerprint: "before",
    appliedFingerprint: "after",
    valid: true,
  };
}

function renderPage(locked = false) {
  function Harness() {
    const legendJson = useLegendJsonPipeline(true);
    return <LegendJsonPipelinePage legendJson={legendJson} locked={locked} />;
  }
  return render(<Harness />);
}

describe("LegendJsonPipelinePage", () => {
  afterEach(() => {
    cleanup();
    clearLegendJsonProgress();
  });

  beforeEach(() => {
    mocks.run.mockReset();
    mocks.cancel.mockReset().mockResolvedValue(undefined);
    mocks.legendEventHandler = null;
    mocks.run.mockImplementation(
      (command: string, config: Record<string, unknown>) => {
        if (command === "legend-json-list")
          return Promise.resolve(page(Number(config.offset ?? 0)));
        if (command === "legend-json-list-backups") {
          return Promise.resolve({ items: [], total: 0 });
        }
        if (command === "legend-json-estimate") {
          return Promise.resolve({
            items: 60,
            estimatedTokens: 1200,
            estimatedApiCalls: 2,
          });
        }
        if (command === "legend-json-translate")
          return new Promise(() => undefined);
        return Promise.resolve({});
      },
    );
  });

  it("phân trang backend, estimate, xác nhận dịch và hủy job", async () => {
    renderPage();
    await screen.findByText("原文 0");

    fireEvent.click(screen.getByRole("button", { name: "Trang sau" }));
    await screen.findByText("原文 50");
    expect(mocks.run).toHaveBeenCalledWith(
      "legend-json-list",
      expect.objectContaining({ offset: 50, limit: 50, status: "New" }),
    );

    fireEvent.click(screen.getByRole("button", { name: "Ước tính" }));
    await screen.findByRole("alertdialog");
    expect(mocks.run).toHaveBeenCalledWith(
      "legend-json-estimate",
      expect.objectContaining({ status: "New", forceRetranslate: false }),
    );
    fireEvent.click(screen.getByRole("button", { name: "Bắt đầu dịch" }));
    await screen.findByText("Đang dịch");

    act(() => {
      mocks.legendEventHandler?.({
        jobId: "legend-json-job",
        type: "progress",
        payload: {
          command: "legend-json-translate",
          processed: 10,
          total: 60,
        },
      });
    });
    fireEvent.click(screen.getByRole("button", { name: "Hủy" }));
    await waitFor(() =>
      expect(mocks.cancel).toHaveBeenCalledWith("legend-json-job"),
    );
  });

  it("giữ lựa chọn tường minh qua nhiều trang và gửi đúng hash", async () => {
    renderPage();
    await screen.findByText("原文 0");

    fireEvent.click(
      screen.getByRole("checkbox", { name: "Chọn toàn bộ theo bộ lọc" }),
    );
    fireEvent.click(screen.getByRole("checkbox", { name: "Chọn 原文 0" }));
    fireEvent.click(screen.getByRole("button", { name: "Trang sau" }));
    await screen.findByText("原文 50");
    fireEvent.click(screen.getByRole("checkbox", { name: "Chọn 原文 50" }));
    fireEvent.click(screen.getByRole("button", { name: "Ước tính" }));

    await screen.findByRole("alertdialog");
    expect(mocks.run).toHaveBeenCalledWith(
      "legend-json-estimate",
      expect.objectContaining({ hashes: ["hash-0", "hash-50"] }),
    );
  });

  it("hiển thị Job Console và chuyển sang mục đã dịch khi job hoàn tất", async () => {
    mocks.run.mockImplementation(
      (command: string, config: Record<string, unknown>) => {
        if (command === "legend-json-list") {
          return Promise.resolve(
            config.status === "Translated"
              ? translatedPage()
              : page(Number(config.offset ?? 0)),
          );
        }
        if (command === "legend-json-list-backups") {
          return Promise.resolve({ items: [], total: 0 });
        }
        if (command === "legend-json-estimate") {
          return Promise.resolve({
            items: 1,
            estimatedTokens: 20,
            estimatedApiCalls: 1,
          });
        }
        if (command === "legend-json-translate") {
          return Promise.resolve({ translated: 1, reused: 0 });
        }
        return Promise.resolve({});
      },
    );

    renderPage();
    await screen.findByText("原文 0");
    fireEvent.click(screen.getByRole("button", { name: "Ước tính" }));
    fireEvent.click(
      await screen.findByRole("button", { name: "Bắt đầu dịch" }),
    );

    expect(await screen.findByText("Bản dịch 0")).toBeInTheDocument();
    await waitFor(() =>
      expect(mocks.run).toHaveBeenCalledWith(
        "legend-json-list",
        expect.objectContaining({ status: "Translated" }),
      ),
    );

    act(() => {
      mocks.legendEventHandler?.({
        jobId: "legend-json-job",
        type: "completed",
        payload: {
          command: "legend-json-translate",
          title: "Hoàn tất dịch JSON",
          description: "Đã lưu target vào SQLite incremental.",
        },
      });
    });
    expect(await screen.findByText("Hoàn tất dịch JSON")).toBeInTheDocument();
  });

  it("hiện thanh tiến trình khi job active và bật Hủy sau started", async () => {
    renderPage();
    await screen.findByText("原文 0");
    expect(screen.queryByText("Đang dịch")).not.toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Ước tính" }));
    fireEvent.click(
      await screen.findByRole("button", { name: "Bắt đầu dịch" }),
    );
    expect(await screen.findByText("Đang dịch")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Hủy" })).toBeDisabled();

    act(() => {
      mocks.legendEventHandler?.({
        jobId: "legend-json-job",
        type: "started",
        payload: { command: "legend-json-translate" },
      });
    });
    expect(screen.getByRole("button", { name: "Hủy" })).toBeEnabled();
  });

  it("hiển thị chi tiết lỗi QA và thay đổi Preview", async () => {
    mocks.run.mockImplementation(
      (command: string, config: Record<string, unknown>) => {
        if (command === "legend-json-list")
          return Promise.resolve(page(Number(config.offset ?? 0)));
        if (command === "legend-json-list-backups") {
          return Promise.resolve({ items: [], total: 0 });
        }
        if (command === "legend-json-preview") {
          return Promise.resolve({
            previewId: "preview-1",
            scanId: "scan-1",
            fingerprint: "fingerprint",
            mainFingerprint: "main",
            outputFingerprint: "output",
            mainPath: "C:\\AutoGeneratedTranslations.txt",
            changeCount: 1,
            changes: [
              {
                kind: "append",
                sourceHash: "hash-0",
                source: "原文 0",
                before: null,
                after: "Bản dịch",
                line: null,
              },
            ],
            qa: {
              blocking: true,
              errors: 1,
              warnings: 0,
              issues: [
                {
                  severity: "error",
                  rule: "protected-token",
                  detail: "Thiếu placeholder",
                  source: "原文 0",
                  sourceHash: "hash-0",
                },
              ],
            },
          });
        }
        return Promise.resolve({});
      },
    );
    renderPage();
    await screen.findByText("原文 0");

    fireEvent.click(screen.getByRole("button", { name: "Preview + QA" }));

    expect(
      await screen.findByText("Placeholder/tag lệch nguồn"),
    ).toBeInTheDocument();
    expect(screen.getByText("Thiếu placeholder")).toBeInTheDocument();
    fireEvent.click(
      screen.getByRole("tab", { name: "Thay đổi dự kiến (1)" }),
    );
    expect(await screen.findByText("Thêm")).toBeInTheDocument();
    expect(screen.getByText("Bản dịch")).toBeInTheDocument();
    expect(screen.queryByText("Thiếu placeholder")).not.toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: "Apply có backup" }),
    ).toBeDisabled();
  });

  it("lọc Chi tiết QA theo lỗi khi Preview bị chặn", async () => {
    mocks.run.mockImplementation(
      (command: string, config: Record<string, unknown>) => {
        if (command === "legend-json-list")
          return Promise.resolve(page(Number(config.offset ?? 0)));
        if (command === "legend-json-list-backups") {
          return Promise.resolve({ items: [], total: 0 });
        }
        if (command === "legend-json-preview") {
          return Promise.resolve({
            previewId: "preview-2",
            scanId: "scan-1",
            fingerprint: "fingerprint",
            mainFingerprint: "main",
            outputFingerprint: "output",
            mainPath: "C:\\AutoGeneratedTranslations.txt",
            changeCount: 1,
            changes: [],
            qa: {
              blocking: true,
              errors: 1,
              warnings: 1,
              issues: [
                {
                  severity: "warning",
                  rule: "han-remaining",
                  detail: "Target còn chữ Hán",
                  source: "名字",
                  sourceHash: "hash-w",
                },
                {
                  severity: "error",
                  rule: "empty-target",
                  detail: "Target rỗng",
                  source: "原文",
                  sourceHash: "hash-e",
                },
              ],
            },
          });
        }
        return Promise.resolve({});
      },
    );
    renderPage();
    await screen.findByText("原文 0");
    fireEvent.click(screen.getByRole("button", { name: "Preview + QA" }));

    expect(await screen.findByText("Bản dịch rỗng")).toBeInTheDocument();
    expect(screen.queryByText("Còn chữ Hán")).not.toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Cảnh báo (1)" }));
    expect(await screen.findByText("Còn chữ Hán")).toBeInTheDocument();
    expect(screen.queryByText("Bản dịch rỗng")).not.toBeInTheDocument();
  });

  it("lọc Chi tiết QA theo loại lỗi", async () => {
    mocks.run.mockImplementation(
      (command: string, config: Record<string, unknown>) => {
        if (command === "legend-json-list")
          return Promise.resolve(page(Number(config.offset ?? 0)));
        if (command === "legend-json-list-backups") {
          return Promise.resolve({ items: [], total: 0 });
        }
        if (command === "legend-json-preview") {
          return Promise.resolve({
            previewId: "preview-3",
            scanId: "scan-1",
            fingerprint: "fingerprint",
            mainFingerprint: "main",
            outputFingerprint: "output",
            mainPath: "C:\\AutoGeneratedTranslations.txt",
            changeCount: 2,
            changes: [],
            qa: {
              blocking: true,
              errors: 2,
              warnings: 0,
              issues: [
                {
                  severity: "error",
                  rule: "empty-target",
                  detail: "Target rỗng",
                  source: "原文 A",
                  sourceHash: "hash-e",
                },
                {
                  severity: "error",
                  rule: "protected-token",
                  detail: "Placeholder/tag lệch nguồn",
                  source: "原文 B",
                  sourceHash: "hash-p",
                },
              ],
            },
          });
        }
        return Promise.resolve({});
      },
    );
    renderPage();
    await screen.findByText("原文 0");
    fireEvent.click(screen.getByRole("button", { name: "Preview + QA" }));

    expect(await screen.findByText("Target rỗng")).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: "Placeholder/tag lệch nguồn (1)" }),
    ).toBeInTheDocument();

    fireEvent.click(
      screen.getByRole("button", { name: "Placeholder/tag lệch nguồn (1)" }),
    );
    expect(screen.getAllByText("Placeholder/tag lệch nguồn").length).toBeGreaterThan(
      0,
    );
    expect(screen.queryByText("Target rỗng")).not.toBeInTheDocument();
  });

  it("Apply dòng OK khi Preview bị chặn nhưng còn thay đổi sạch", async () => {
    mocks.run.mockImplementation(
      (command: string, config: Record<string, unknown>) => {
        if (command === "legend-json-list")
          return Promise.resolve(page(Number(config.offset ?? 0)));
        if (command === "legend-json-list-backups") {
          return Promise.resolve({ items: [], total: 0 });
        }
        if (command === "legend-json-preview") {
          return Promise.resolve({
            previewId: "preview-4",
            scanId: "scan-1",
            fingerprint: "fingerprint",
            mainFingerprint: "main",
            outputFingerprint: "output",
            mainPath: "C:\\AutoGeneratedTranslations.txt",
            changeCount: 2,
            changes: [
              {
                kind: "append",
                sourceHash: "hash-ok",
                source: "原文 OK",
                before: null,
                after: "Bản dịch",
                line: null,
              },
              {
                kind: "append",
                sourceHash: "hash-e",
                source: "#标题",
                before: null,
                after: "Tiêu đề",
                line: null,
              },
            ],
            qa: {
              blocking: true,
              errors: 1,
              warnings: 0,
              issues: [
                {
                  severity: "error",
                  rule: "serialization-roundtrip",
                  detail: "Source/target không đọc lại đúng sau serialization",
                  source: "#标题",
                  sourceHash: "hash-e",
                },
              ],
            },
          });
        }
        if (command === "legend-json-apply") {
          return Promise.resolve({
            previewId: "preview-4",
            backupId: "backup-ok",
            backupPath: "C:\\backup.txt",
            manifestPath: "C:\\manifest.json",
            outputPath: "C:\\AutoGeneratedTranslations.txt",
            outputFingerprint: "after",
            appliedCount: 1,
            skippedCount: 1,
            instruction: "Nhấn Alt+R trong game.",
          });
        }
        return Promise.resolve({});
      },
    );
    renderPage();
    await screen.findByText("原文 0");
    fireEvent.click(screen.getByRole("button", { name: "Preview + QA" }));

    expect(
      await screen.findByRole("button", { name: "Apply dòng OK" }),
    ).toBeEnabled();
    expect(screen.getByRole("button", { name: "Apply có backup" })).toBeDisabled();

    fireEvent.click(screen.getByRole("button", { name: "Apply dòng OK" }));
    expect(
      await screen.findByRole("heading", { name: "Apply dòng OK?" }),
    ).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Backup & Apply dòng OK" }));

    await waitFor(() =>
      expect(mocks.run).toHaveBeenCalledWith(
        "legend-json-apply",
        expect.objectContaining({
          previewId: "preview-4",
          skipErrors: true,
        }),
      ),
    );
  });

  it("icon QA hiện dòng tương ứng trên bảng Text đã phát hiện", async () => {
    mocks.run.mockImplementation(
      (command: string, config: Record<string, unknown>) => {
        if (command === "legend-json-list")
          return Promise.resolve(page(Number(config.offset ?? 0)));
        if (command === "legend-json-list-backups") {
          return Promise.resolve({ items: [], total: 0 });
        }
        if (command === "legend-json-preview") {
          return Promise.resolve({
            previewId: "preview-5",
            scanId: "scan-1",
            fingerprint: "fingerprint",
            mainFingerprint: "main",
            outputFingerprint: "output",
            mainPath: "C:\\AutoGeneratedTranslations.txt",
            changeCount: 1,
            changes: [],
            qa: {
              blocking: true,
              errors: 1,
              warnings: 0,
              issues: [
                {
                  severity: "error",
                  rule: "empty-target",
                  detail: "Target rỗng",
                  source: "原文 0",
                  sourceHash: "hash-0",
                },
              ],
            },
          });
        }
        return Promise.resolve({});
      },
    );
    renderPage();
    await screen.findByText("原文 0");
    fireEvent.click(screen.getByRole("button", { name: "Preview + QA" }));
    await screen.findByText("Target rỗng");

    fireEvent.click(
      screen.getByRole("button", {
        name: "Hiện trong bảng Text đã phát hiện",
      }),
    );

    await waitFor(() =>
      expect(mocks.run).toHaveBeenCalledWith(
        "legend-json-list",
        expect.objectContaining({
          search: "原文 0",
          status: "All",
        }),
      ),
    );
    expect(screen.getByLabelText("Tìm text Legend JSON")).toHaveValue("原文 0");
    expect(screen.getByLabelText("Lọc theo trạng thái")).toHaveTextContent(
      "Tất cả",
    );
  });

  it("hiện card Backup Apply khi không có preview", async () => {
    mocks.run.mockImplementation((command: string) => {
      if (command === "legend-json-list") return Promise.resolve(page());
      if (command === "legend-json-list-backups") {
        return Promise.resolve({ items: [backupItem()], total: 1 });
      }
      return Promise.resolve({});
    });

    renderPage();
    expect(await screen.findByText("Backup Apply")).toBeInTheDocument();
    expect(screen.getByText("backup-1")).toBeInTheDocument();
    expect(
      screen.queryByRole("button", { name: "Apply có backup" }),
    ).not.toBeInTheDocument();
  });

  it("mở dialog force restore khi fingerprint không khớp", async () => {
    mocks.run.mockImplementation(
      (command: string, config: Record<string, unknown>) => {
        if (command === "legend-json-list") return Promise.resolve(page());
        if (command === "legend-json-list-backups") {
          return Promise.resolve({ items: [backupItem()], total: 1 });
        }
        if (command === "legend-json-restore") {
          if (!config.force) {
            return Promise.reject({
              message:
                "File hiện tại đã thay đổi sau Apply; cần xác nhận force để Restore",
            });
          }
          return Promise.resolve({
            backupId: "backup-1",
            outputPath: "C:\\AutoGeneratedTranslations.txt",
            fingerprint: "after",
            restored: true,
          });
        }
        return Promise.resolve({});
      },
    );

    renderPage();
    fireEvent.click(
      await screen.findByRole("button", { name: "Restore backup mới nhất" }),
    );
    expect(
      await screen.findByRole("heading", { name: "File chính đã đổi sau Apply" }),
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Force restore" }));
    await waitFor(() =>
      expect(mocks.run).toHaveBeenCalledWith(
        "legend-json-restore",
        expect.objectContaining({ backupId: "backup-1", force: true }),
      ),
    );
  });

  it("khóa filter và paginator khi job đang chạy", async () => {
    renderPage();
    await screen.findByText("原文 0");

    fireEvent.click(screen.getByRole("button", { name: "Ước tính" }));
    fireEvent.click(
      await screen.findByRole("button", { name: "Bắt đầu dịch" }),
    );
    expect(await screen.findByText("Đang dịch")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Hủy" })).toBeDisabled();
    expect(screen.getByLabelText("Lọc theo trạng thái")).toBeDisabled();
    expect(screen.getByRole("button", { name: "Trang sau" })).toBeDisabled();

    act(() => {
      mocks.legendEventHandler?.({
        jobId: "legend-json-job",
        type: "started",
        payload: { command: "legend-json-translate" },
      });
    });
    expect(screen.getByRole("button", { name: "Hủy" })).toBeEnabled();
    expect(screen.getByLabelText("Lọc theo trạng thái")).toBeDisabled();
    expect(screen.getByRole("button", { name: "Trang sau" })).toBeDisabled();
  });

  it("khóa Quét khi locked bởi job khác", async () => {
    renderPage(true);
    await screen.findByText("原文 0");
    expect(
      screen.getByRole("button", { name: "Quét incremental" }),
    ).toBeDisabled();
  });
});
